import ast
from pathlib import Path

p_path = Path("products_data.py")
content = p_path.read_text(encoding="utf-8")

new_items_code = """
    {
        "slug": "heavy-duty-locking-drawer-slide",
        "cat": "hardware",
        "name": "53mm Heavy Duty 3-Section Locking Drawer Slide",
        "badge": "Bestseller",
        "price": "$4.20 - $6.30 /pr",
        "moq": "MOQ 1 pair",
        "img": "/images/heavy-duty-locking-drawer-slide.jpg",
        "src": "https://detail.1688.com/offer/1006740221581.html",
        "desc": "Industrial-grade heavy duty drawer slide constructed from 2.0mm thickened cold-rolled steel, featuring a robust locking mechanism for safety and stability. The 53mm wide profile supports up to 120kg (265 lbs), making it ideal for tool cabinets, RV modifications, machinery housing, and heavy-duty industrial storage. The 3-section full extension design allows complete access to the drawer contents, while the precision ball bearings ensure smooth and quiet operation even under maximum load. The integrated lock prevents accidental opening or sliding in mobile environments. Built to last with a corrosion-resistant finish, this sliding track is a reliable choice for professional workshops and specialized vehicle fit-outs. Factory-direct availability ensures consistent quality and competitive pricing for bulk procurement. Whether upgrading a mobile service van or installing high-capacity storage in a factory setting, these locking slides provide the strength and security required for demanding professional applications in the 2026 hardware market.",
        "specs": [
            ("Material", "Thickened Cold-Rolled Steel"),
            ("Width", "53 mm"),
            ("Thickness", "2.0 mm"),
            ("Load Capacity", "120 kg (265 lbs)"),
            ("Feature", "Safety Lock / 3-Section Full Extension"),
            ("Application", "Tool Cabinets, RVs, Industrial Shelving"),
        ],
        "points": [
            "Heavy duty 2.0mm steel supports up to 120kg",
            "Safety lock prevents accidental sliding in RVs",
            "Precision steel ball bearings for smooth action",
            "Full extension allows complete drawer access",
        ],
        "related": ["industrial-drawer-sliding-track", "soft-close-cabinet-slide", "heavy-duty-swivel-caster"],
    },
    {
        "slug": "industrial-drawer-sliding-track",
        "cat": "hardware",
        "name": "Reinforced 53mm Industrial Heavy Duty Rail with Lock",
        "badge": "Hot",
        "price": "$3.80 - $5.70 /pr",
        "moq": "MOQ 1 pair",
        "img": "/images/industrial-drawer-sliding-track.jpg",
        "src": "https://detail.1688.com/offer/1008722033983.html",
        "desc": "High-capacity industrial sliding rail reinforced for extreme durability in demanding environments. This 53mm wide track is manufactured from high-strength steel with a precision-engineered 3-section telescopic mechanism for effortless full extension. The built-in locking lever provides secure positioning, locking the drawer firmly when fully closed or fully opened. Designed for heavy-duty storage racks, automated machinery drawers, and professional tool chests, it offers exceptional lateral stability and smooth gliding motion. The reinforced structure minimizes sag even at full extension under significant weight. Surface-treated for enhanced wear resistance and longevity. For distributors and manufacturers, this rail delivers the industrial-grade performance expected in modern logistics and manufacturing facilities. Its robust construction reduces maintenance needs and ensures operational safety across a wide range of high-load storage configurations.",
        "specs": [
            ("Material", "High-Strength Reinforced Steel"),
            ("Width", "53 mm"),
            ("Mechanism", "3-Section Telescopic"),
            ("Lock Type", "Bi-directional Safety Lock"),
            ("Finish", "Anti-Corrosion Zinc Plated"),
            ("Installation", "Side Mount Standard"),
        ],
        "points": [
            "Industrial grade reinforcement for heavy loads",
            "Bi-directional lock for maximum safety",
            "Smooth 3-section telescopic extension",
            "Resistant to sag and lateral vibration",
        ],
        "related": ["heavy-duty-locking-drawer-slide", "soft-close-cabinet-slide", "heavy-duty-pu-iron-caster"],
    },
    {
        "slug": "soft-close-cabinet-slide",
        "cat": "hardware",
        "name": "Full Extension Soft-Close Ball Bearing Drawer Slide",
        "badge": "New",
        "price": "$4.30 - $6.50 /pr",
        "moq": "MOQ 1 pair",
        "img": "/images/soft-close-cabinet-slide.jpg",
        "src": "https://detail.1688.com/offer/817661656098.html",
        "desc": "Premium soft-close drawer slide featuring advanced hydraulic damping technology for silent and controlled closing. Crafted from high-grade black steel with a 1.2mm thickness, these slides provide a sleek modern aesthetic and superior durability for kitchen cabinets, office furniture, and high-end residential joinery. The 3-section full extension mechanism uses precision-machined ball bearings to deliver an exceptionally smooth glide, while the integrated soft-close buffer prevents slamming and protects the cabinet structure. The push-to-open variant is also available for minimalist handle-less designs. Easy to install with standard side mounting, these slides are an essential upgrade for modern interior fit-outs in 2026. Factory-tested for over 50,000 cycles to ensure long-term reliability. Suitable for furniture manufacturers and hardware wholesalers seeking high-performance components that enhance the end-user experience through quiet functionality and modern design.",
        "specs": [
            ("Material", "High-Grade Black Steel"),
            ("Thickness", "1.2 x 1.2 x 1.5 mm"),
            ("Closure Type", "Hydraulic Soft-Close / Push-to-Open"),
            ("Mounting", "Side Mount"),
            ("Load Rating", "45 kg (100 lbs)"),
            ("Extension", "3-Section Full Travel"),
        ],
        "points": [
            "Silent hydraulic damping for soft-close",
            "Durable black steel with sleek finish",
            "Precision ball bearings for smooth gliding",
            "Tested for 50,000+ opening/closing cycles",
        ],
        "related": ["heavy-duty-locking-drawer-slide", "black-aluminum-cabinet-handle", "cabinet-hinge-repair-plate"],
    },
    {
        "slug": "crv-woodworking-chisel-set",
        "cat": "hand-tools",
        "name": "Professional CR-V Steel Woodworking Chisel (Beech Handle)",
        "badge": "Bestseller",
        "price": "$0.80 - $1.20 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/crv-woodworking-chisel-set.jpg",
        "src": "https://detail.1688.com/offer/919563704115.html",
        "desc": "High-precision woodworking chisel forged from premium Chrome Vanadium (CR-V) alloy steel for exceptional hardness and edge retention. The blade features a precision-ground bevel and is polished to a mirror finish for clean, accurate cuts in soft and hard woods. Equipped with an ergonomic beech wood handle that is reinforced with a steel hoop to withstand heavy mallet strikes during mortising and heavy carving tasks. The through-tang construction ensures maximum force transfer and structural integrity. Ideal for professional carpenters, luthiers, and hobbyists, this tool is designed for intricate detail work, joinery, and general timber shaping. The blade arrives sharp and ready for immediate use, reducing setup time in the workshop. Available in multiple widths from 6mm to 38mm to cover all woodworking needs. This professional-grade chisel is a staple for tool distributors and woodworking supply shops focusing on quality and performance.",
        "specs": [
            ("Blade Material", "Chrome Vanadium Steel (CR-V)"),
            ("Handle Material", "Natural Beech Wood"),
            ("Reinforcement", "Steel Ferrule & Hoop"),
            ("Width Range", "6mm - 38mm available"),
            ("Construction", "Through-Tang for Strength"),
            ("Finish", "Mirror Polished Blade"),
        ],
        "points": [
            "Forged CR-V steel for lasting sharpness",
            "Natural beech handle with mallet reinforcement",
            "Precision ground bevel for accurate joinery",
            "Through-tang design for superior durability",
        ],
        "related": ["65mn-wood-handsaw", "mini-aluminum-wood-plane", "72-tooth-ratchet-wrench-set"],
    },
    {
        "slug": "wide-opening-short-wrench",
        "cat": "hand-tools",
        "name": "8-Inch Short Handle Wide Opening Adjustable Wrench",
        "badge": "Hot",
        "price": "$1.90 - $2.80 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/wide-opening-short-wrench.jpg",
        "src": "https://detail.1688.com/offer/995705077460.html",
        "desc": "Versatile 8-inch adjustable wrench featuring a unique short handle and an extra-wide jaw opening for superior access in confined spaces. Precision forged from high-strength chrome vanadium steel, the jaws can open up to 45mm, allowing one compact tool to handle larger nuts and pipe fittings typically requiring a much larger wrench. The slim profile head and short handle are specifically designed for plumbing work, automotive repairs, and HVAC maintenance in tight spots where standard tools cannot maneuver. The smooth-acting adjustment screw provides precise jaw control, while the laser-etched metric scale ensures quick and accurate sizing. Features a durable multi-layer plating for enhanced rust resistance in humid environments. The ergonomic handle design reduces hand fatigue during repetitive use. This specialized wrench is a high-demand item for professional plumbers and maintenance technicians looking for a compact, high-torque solution for modern installation tasks.",
        "specs": [
            ("Material", "Chrome Vanadium Steel (CR-V)"),
            ("Length", "203 mm (8 inch)"),
            ("Jaw Capacity", "Up to 45 mm"),
            ("Finish", "Anti-Rust Multi-Layer Plating"),
            ("Scale", "Laser-Etched Metric"),
            ("Weight", "454 g"),
        ],
        "points": [
            "Extra wide 45mm opening in a compact body",
            "Short handle for tight plumbing & HVAC spaces",
            "High-torque forged CR-V steel construction",
            "Precise laser-etched scale for fast sizing",
        ],
        "related": ["mini-adjustable-wrench-set", "quick-adjust-pipe-wrench", "industrial-water-pump-pliers"],
    },
    {
        "slug": "mini-adjustable-wrench-set",
        "cat": "hand-tools",
        "name": "2.5-Inch & 4-Inch Mini Precision Adjustable Wrench Set",
        "badge": "New",
        "price": "$0.50 - $0.80 /pc",
        "moq": "MOQ 20 pcs",
        "img": "/images/mini-adjustable-wrench-set.jpg",
        "src": "https://detail.1688.com/offer/995705077460.html",
        "desc": "Ultra-compact precision adjustable wrench set including 2.5-inch and 4-inch models, designed for delicate tasks and micro-adjustments. Forged from high-quality carbon steel with a durable polished finish, these mini wrenches are perfect for electronics repair, model making, jewelry assembly, and small equipment maintenance. Despite their small size, they offer a reliable grip and smooth worm-gear adjustment for precise jaw positioning. The integrated keychain hole on the 2.5-inch model makes it a convenient EDC (Everyday Carry) tool for technicians and outdoor enthusiasts. These tools are indispensable for working with small nuts and bolts in restricted areas where standard wrenches are too bulky. Ideal for gift sets, toolkit expansions, and hardware retailers. The mini size also makes them a popular choice for promotional items and impulse purchases in the professional tool market. Reliable performance meets extreme portability in this essential precision fastening set for the 2026 workshop.",
        "specs": [
            ("Material", "Forged Carbon Steel"),
            ("Sizes Included", "2.5 inch / 4 inch"),
            ("Finish", "Mirror Polished / Black Electrophoresis"),
            ("Jaw Opening", "Precision Micro-Adjustment"),
            ("Portability", "Keychain-ready 2.5-inch model"),
            ("Application", "Electronics, Jewelry, Micro-Mechanics"),
        ],
        "points": [
            "Ultra-compact for micro-precision tasks",
            "Ideal for electronics and delicate repairs",
            "Smooth worm-gear for precise jaw control",
            "Durable forged steel with polished finish",
        ],
        "related": ["wide-opening-short-wrench", "118pc-precision-screwdriver-set", "5-inch-curved-needle-nose-pliers"],
    },
    {
        "slug": "precision-electric-screwdriver-pen",
        "cat": "power-tools",
        "name": "3.6V Mini Precision Pen-Style Cordless Electric Screwdriver",
        "badge": "Hot",
        "price": "$3.80 - $5.80 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/precision-electric-screwdriver-pen.jpg",
        "src": "https://detail.1688.com/offer/875345832631.html",
        "desc": "Sleek and powerful 3.6V pen-style cordless electric screwdriver designed for high-precision assembly and repair work. The slim, lightweight body features an ergonomic non-slip grip, making it as comfortable to hold as a standard pen, allowing for effortless control during intricate tasks. Powered by a long-lasting 1300mAh lithium-ion battery, it delivers a steady 250 RPM and 2N.m torque, perfect for servicing smartphones, laptops, cameras, and assembling furniture. The dual-mode operation supports both electric and manual use, providing versatility for various screw types. This precision tool comes with a USB charging cable and a set of high-quality magnetic bits. Its compact design fits easily into pockets or tool bags, making it a favorite for field technicians and DIY electronics enthusiasts. As the demand for portable, high-efficiency tools grows in 2026, this electric screwdriver pen offers the perfect blend of performance, portability, and professional design for the global e-commerce and retail markets.",
        "specs": [
            ("Voltage", "3.6 V / DC"),
            ("Battery Capacity", "1300 mAh Li-ion"),
            ("No-Load Speed", "250 r/min"),
            ("Max Torque", "2 N.m"),
            ("Charging Time", "5 - 7 Hours"),
            ("Operating Modes", "Electric / Manual Dual Mode"),
        ],
        "points": [
            "Ultra-slim pen design for precision control",
            "Rechargeable Li-ion battery with USB charging",
            "Dual-mode: use electric or manual torque",
            "Ideal for electronics and small appliances",
        ],
        "related": ["118pc-precision-screwdriver-set", "mini-cordless-screwdriver-set", "brushless-cordless-drill"],
    },
    {
        "slug": "high-speed-cordless-drill-kit",
        "cat": "power-tools",
        "name": "21V Brushless High Speed Cordless Electric Drill Kit",
        "badge": "New",
        "price": "$19.00 - $29.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/high-speed-cordless-drill-kit.jpg",
        "src": "https://detail.1688.com/offer/1001097427533.html",
        "desc": "Professional-grade 21V brushless cordless drill kit delivering high-speed drilling performance and exceptional torque for construction and woodworking projects. The high-efficiency brushless motor provides 30% more power and 50% longer runtime compared to traditional brushed motors, while minimizing maintenance. This complete kit features two high-capacity lithium batteries and a rapid charger to ensure continuous operation on the job site. The variable speed trigger and adjustable torque settings allow for precise control in different materials, from soft wood to hardened steel. Includes a built-in LED work light for visibility in dark areas and an ergonomic balanced handle for reduced fatigue. The robust keyless chuck makes bit changes fast and secure. Designed for durability and performance, this drill is a reliable workhorse for professional contractors and high-end DIY users. Ideal for global B2B procurement, this kit meets the high standards for professional cordless tools in the 2026 export market.",
        "specs": [
            ("Motor Type", "High-Efficiency Brushless"),
            ("Voltage", "21 V Max"),
            ("Battery", "Dual Li-ion Packs Included"),
            ("Chuck Size", "10 mm (3/8 inch) Keyless"),
            ("Torque Settings", "Multiple + Drilling Mode"),
            ("Kit Components", "Drill, 2 Batteries, Charger, Case"),
        ],
        "points": [
            "Advanced brushless motor for peak efficiency",
            "Complete kit with 2 batteries and fast charger",
            "Variable speed and torque for total control",
            "Ergonomic design for comfortable all-day use",
        ],
        "related": ["brushless-impact-wrench-kit", "brushless-cordless-angle-grinder", "13mm-brushless-cordless-impact-drill"],
    },
    {
        "slug": "pneumatic-reciprocating-file-machine",
        "cat": "pneumatic-tools",
        "name": "Industrial Pneumatic Reciprocating File & Grinding Machine",
        "badge": "Bestseller",
        "price": "$19.00 - $29.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/pneumatic-reciprocating-file-machine.jpg",
        "src": "https://detail.1688.com/offer/574952640289.html",
        "desc": "High-performance reciprocating pneumatic file machine engineered for industrial deburring, shaping, and surface finishing in metalworking and mold making. Delivering up to 6,500 strokes per minute with a 5mm-10mm reciprocating travel, this tool provides efficient material removal in tight spaces where rotary grinders cannot reach. The lightweight alloy body and vibration-damping rubber sleeve ensure comfort during extended use, while the low-noise exhaust system improves the working environment. The precision collet securely holds a variety of file shapes including flat, round, and triangular. Built with industrial-grade bearings and a hardened piston for long service life under heavy workshop usage. Essential for die cast cleaning, furniture carving finishing, and precision metal fabrication. Easy to maintain with rear oiling ports, this pneumatic file is a cost-effective and reliable solution for professional workshops and assembly lines worldwide. Requires a standard air compressor setup (6.2kgf/cm²) for optimal performance.",
        "specs": [
            ("Stroke Frequency", "Up to 6,500 bpm"),
            ("Stroke Length", "5 mm - 10 mm reciprocating"),
            ("Air Consumption", "0.2 m³/min"),
            ("Operating Pressure", "6.2 kgf/cm² (90 psi)"),
            ("Body Material", "High-Strength Alloy"),
            ("Feature", "Vibration-Damping / Low-Noise Exhaust"),
        ],
        "points": [
            "High stroke frequency for rapid deburring",
            "Reciprocating action for tight-space shaping",
            "Durable alloy body with vibration control",
            "Compatible with multiple file and saw shapes",
        ],
        "related": ["professional-pneumatic-air-saw", "air-die-grinder-6mm", "pneumatic-needle-scaler"],
    },
    {
        "slug": "professional-pneumatic-air-saw",
        "cat": "pneumatic-tools",
        "name": "Heavy Duty Professional Pneumatic Reciprocating Air Saw",
        "badge": "Hot",
        "price": "$12.00 - $18.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/professional-pneumatic-air-saw.jpg",
        "src": "https://detail.1688.com/offer/1000684226709.html",
        "desc": "Professional-grade pneumatic reciprocating air saw designed for rapid cutting of sheet metal, aluminum, and plastics in automotive and industrial workshops. This powerful tool delivers a high-speed reciprocating action of 9,000 RPM with a 5mm stroke, enabling clean and fast cuts through metal plates up to 1.6mm thickness. The lightweight and ergonomic design allows for easy one-handed operation and precise control in complex cutting paths. Features a robust safety lever throttle to prevent accidental starts and a built-in air filter to protect the motor from debris. The alloy housing and vibration-resistant handle provide durability and comfort for heavy-duty daily use. Ideal for auto body repair, manufacturing, and maintenance tasks where cordless or electric saws lack the necessary speed or duty cycle. Factory-direct sourcing ensures professional performance with significant cost savings. This air saw is a vital addition to any professional air tool inventory, providing the reliability and power needed for 2026 industrial cutting standards.",
        "specs": [
            ("Cutting Speed", "9,000 RPM"),
            ("Stroke Length", "5 mm"),
            ("Cutting Capacity", "Metal ≤1.6mm / Alu ≤2mm"),
            ("Air Inlet", "1/4 inch NPT"),
            ("Air Pressure", "6.3 - 8.0 kg/cm²"),
            ("Weight", "0.73 kg"),
        ],
        "points": [
            "Powerful 9,000 RPM for high-speed metal cutting",
            "Lightweight 0.73kg body for one-hand operation",
            "Safety trigger and bumper for secure operation",
            "Ideal for auto body and sheet metal workshops",
        ],
        "related": ["pneumatic-reciprocating-file-machine", "pneumatic-metal-shear", "4-inch-pneumatic-angle-grinder"],
    },
"""

search_marker = '    },\n]'
replacement = '    },\n' + new_items_code + ']'

if search_marker in content:
    new_content = content.replace(search_marker, replacement, 1)
    p_path.write_text(new_content, encoding="utf-8")
    print("Successfully appended 10 items to products_data.py")
else:
    print("Could not find the end of the PRODUCTS list marker.")
