# -*- coding: utf-8 -*-
"""Best Hardware Tools site product data. Prices = FOB USD estimates (CNY/7.1)."""

SITE = {
    "brand": "Best Hardware Tools",
    "short": "BHT",
    "domain": "besthardwaretools.com",
    "tagline": "One-Stop Hardware & Tools Supplier for Global Buyers",
    "whatsapp": "8618669693290",
    "email": "yale@mahjongbest.com",
    "formspree": "xeeynyba",
    "ga4": "G-5J9VBPKTB4",
    "clarity": "xtrv7vr8dn",
    "bank_beneficiary": "Linyi Strawberry International Trade Co., Ltd",
    "bank_account": "63003927994",
    "bank_swift": "CHASHKHH / CHASHKHHXXX",
    "bank_note": "USD Payments: Recommend using US J.P. Morgan (CHASUS33) as transit bank to reduce forex risk. This account cannot receive payments from Russia and Belarus.",
}

CATEGORIES = [
    {"id": "hardware", "name": "Hardware", "nav": "Hardware"},
    {"id": "hand-tools", "name": "Hand Tools", "nav": "Hand Tools"},
    {"id": "power-tools", "name": "Power Tools", "nav": "Power Tools"},
    {"id": "pneumatic-tools", "name": "Pneumatic Tools", "nav": "Pneumatic Tools"},
]

PRODUCTS = [
    {
        "slug": "stainless-steel-soft-close-hinge",
        "cat": "hardware",
        "name": "304 Stainless Steel Hydraulic Soft-Close Hinge",
        "badge": "Bestseller",
        "price": "$0.28 - $0.42 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/stainless-steel-soft-close-hinge.jpg",
        "src": "https://detail.1688.com/offer/708534731229.html",
        "desc": "Precision-engineered 304 stainless steel hinge with integrated hydraulic damping for silent, soft-close cabinet doors. The 2.0mm thickened body delivers outstanding rigidity and long service life, while the self-closing mechanism protects cabinets from slamming damage. Ideal for kitchen cabinets, wardrobes and commercial furniture, this hinge suits both new builds and retrofits. Factory-direct supply supports custom finishes, bulk packaging and OEM branding for furniture manufacturers and hardware distributors worldwide. Ideal for hotel joinery, apartment fit-outs and cabinet workshops where silent closing is a selling point, this hinge reduces warranty callbacks caused by slamming doors. Kitchens, wardrobes and vanities with heavy doors all benefit from the smooth hydraulic damped action, while the corrosion-resistant 304 grade body holds up in humid coastal climates and high-moisture commercial settings.",
        "specs": [
            ("Material", "304 Stainless Steel"),
            ("Thickness", "2.0 mm"),
            ("Type", "Hydraulic Damping / Soft-Close"),
            ("Opening", "Full Overlay (Large Bend)"),
            ("Application", "Cabinet, Wardrobe, Kitchen Door"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Silent hydraulic soft-close prevents door slamming",
            "2.0mm 304 stainless steel - rust resistant & durable",
            "Self-locking clip-on design for fast installation",
            "Factory-direct with OEM & custom packaging support",
            "Standard 35mm cup fits most cabinet doors - easy retrofit",
        ],
        "related": ["black-aluminum-cabinet-handle", "heavy-duty-swivel-caster", "72-tooth-ratchet-wrench-set"],
    },
    {
        "slug": "black-aluminum-cabinet-handle",
        "cat": "hardware",
        "name": "Black Anodized Aluminum Cabinet Handle / Drawer Pull",
        "badge": "Hot",
        "price": "$0.15 - $0.25 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/black-aluminum-cabinet-handle.jpg",
        "src": "https://detail.1688.com/offer/1037766581644.html",
        "desc": "Modern minimalist cabinet handle machined from solid aluminum with a durable anodized black finish. The clean, slim profile complements contemporary kitchens, wardrobes and office furniture. Available in multiple hole spacings (128mm standard) to match common cabinet panels. Each handle is precision-drilled for accurate alignment and ships with mounting screws. A popular choice for furniture makers, renovation projects and cross-border e-commerce sellers building hardware ranges. Its clean matte black profile also matches the 2026 cabinet hardware trend toward minimal, tactile pulls that anchor modern kitchens, closets and vanities. Whether renovating a single bathroom or fitting out a whole apartment complex, the consistent anodized finish keeps cabinets and drawers visually uniform across large orders. For furniture factories and e-commerce sellers, the slim bar design installs in minutes with the included screws, cutting assembly time on production lines.",
        "specs": [
            ("Material", "Aluminum Alloy"),
            ("Finish", "Anodized Black"),
            ("Hole Spacing", "128 mm (more sizes available)"),
            ("Style", "Modern Minimalist"),
            ("Application", "Cabinet, Drawer, Wardrobe"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Solid aluminum with scratch-resistant anodized finish",
            "Slim modern profile fits most furniture styles",
            "Multiple hole spacings for panel flexibility",
            "Screws included - ready to install",
            "Matte black finish resists fingerprints & wear",
        ],
        "related": ["stainless-steel-soft-close-hinge", "heavy-duty-swivel-caster", "magnetic-screwdriver-set"],
    },
    {
        "slug": "heavy-duty-swivel-caster",
        "cat": "hardware",
        "name": "Heavy Duty Swivel Caster Wheel with Brake",
        "badge": "New",
        "price": "$0.85 - $1.30 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/heavy-duty-swivel-caster.jpg",
        "src": "https://detail.1688.com/offer/728667477642.html",
        "desc": "Rugged swivel caster with integrated brake, built for trolleys, platform carts, racks and industrial equipment. The hardened rubber wheel delivers smooth, quiet rolling on hard floors while the reinforced steel bracket and ball-bearing swivel ensure heavy load capacity and 360-degree maneuverability. The side brake locks the wheel firmly in place for safe stationary work. Available in multiple sizes and load ratings to match your application. Factory-direct pricing for bulk importers and OEM projects. Commonly fitted to workbenches, mobile tool cabinets, warehouse shelving and catering equipment, this caster's side brake gives operators a stable platform during loading and maintenance. It is a dependable upgrade for carts carrying compressors, welders or heavy stock, where smooth rolling and secure parking reduce daily handling effort.",
        "specs": [
            ("Wheel Diameter", "4 inch (more sizes available)"),
            ("Type", "Swivel with Brake"),
            ("Material", "Rubber Wheel + Steel Bracket"),
            ("Application", "Trolley, Platform Cart, Rack"),
            ("Feature", "360° Swivel, Side Brake"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Side brake locks wheel for safe stationary use",
            "Hardened rubber wheel - quiet on hard floors",
            "Reinforced steel bracket for heavy loads",
            "Multiple sizes & load ratings available",
            "Rubber tread protects workshop floors from scuffs",
        ],
        "related": ["stainless-steel-soft-close-hinge", "black-aluminum-cabinet-handle", "air-impact-wrench"],
    },
    {
        "slug": "72-tooth-ratchet-wrench-set",
        "cat": "hand-tools",
        "name": "72-Tooth Dual-Drive Rapid Ratchet Wrench",
        "badge": "Bestseller",
        "price": "$1.35 - $2.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/72-tooth-ratchet-wrench-set.jpg",
        "src": "https://detail.1688.com/offer/1060774840292.html",
        "desc": "High-efficiency dual-drive ratchet wrench combining open-end and box-end functions in one tool. The 72-tooth ratchet mechanism delivers a fine 5-degree swing arc, letting you work in tight spaces without re-positioning. Forged from hardened chrome vanadium steel with a corrosion-resistant black nickel finish and an anti-slip grip, it provides confident torque for automotive, machinery and general maintenance tasks. Available in multiple sizes and as complete sets. Auto repair technicians reach suspension and under-dash bolts faster with the compact dual-drive head, while maintenance teams cover both open-end and box-end jobs without switching tools. For toolbox suppliers and hardware distributors, the corrosion-resistant black nickel finish keeps the wrench shelf-ready, and the full size range lets buyers stock a single reference that serves cars, trucks and plant machinery.",
        "specs": [
            ("Material", "Chrome Vanadium Steel (CR-V)"),
            ("Ratchet", "72-Tooth / 5° Swing Arc"),
            ("Type", "Dual-Drive Open-End & Box-End"),
            ("Size", "13 mm (full size range available)"),
            ("Finish", "Black Nickel Anti-Corrosion"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "72-tooth ratchet - works in tight spaces",
            "Dual drive combines open-end & box-end",
            "Forged CR-V steel with anti-corrosion finish",
            "Ideal for automotive & machinery maintenance",
            "Dual-drive design saves time by reducing tool changes",
        ],
        "related": ["magnetic-screwdriver-set", "industrial-lineman-pliers", "brushless-impact-wrench"],
    },
    {
        "slug": "magnetic-screwdriver-set",
        "cat": "hand-tools",
        "name": "Industrial Magnetic Screwdriver Set (CR-V)",
        "badge": "Hot",
        "price": "$0.36 - $0.55 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/magnetic-screwdriver-set.jpg",
        "src": "https://detail.1688.com/offer/834783626722.html",
        "desc": "Professional-grade screwdriver set featuring hardened chrome vanadium steel shafts with strong magnetic tips that hold screws firmly during fastening. Ergonomic handles provide a comfortable, slip-resistant grip for extended working sessions. This set covers Phillips and slotted (flat) heads in multiple sizes, making it a versatile addition for electricians, mechanics, DIY users and assembly lines. Suitable for household repairs, appliance service and industrial maintenance. Electricians rely on the magnetic tips when working inside switch boxes and appliances, while assembly technicians value the multi-size coverage that reduces tip changes during long production runs. A dependable companion for handymen, locksmiths and electronics repair shops that need one set for everyday fastening.",
        "specs": [
            ("Material", "Chrome Vanadium Steel (CR-V)"),
            ("Tips", "Phillips & Slotted, Magnetic"),
            ("Length", "75 mm shaft (multi sizes)"),
            ("Handle", "Ergonomic Anti-Slip Grip"),
            ("Application", "Electrical, Assembly, DIY"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Strong magnetic tip holds screws securely",
            "Hardened CR-V steel - wear resistant",
            "Ergonomic grip for comfortable use",
            "Multi-size set covers common tasks",
            "Magnetic tips help retrieve dropped screws in tight spots",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "industrial-lineman-pliers", "brushless-cordless-drill"],
    },
    {
        "slug": "industrial-lineman-pliers",
        "cat": "hand-tools",
        "name": "Industrial Grade Lineman Pliers 6\" (CR-V Forged)",
        "badge": "Bestseller",
        "price": "$0.90 - $1.35 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/industrial-lineman-pliers.jpg",
        "src": "https://detail.1688.com/offer/576365440885.html",
        "desc": "Heavy-duty lineman pliers drop-forged from chrome vanadium steel with induction-hardened cutting edges that slice through wire, cable and light metal with ease. The multi-function design integrates cutting, gripping, crimping and stripping functions in one tool. A precision-aligned joint ensures smooth, consistent operation, while the TPR comfort grip reduces hand fatigue. A staple for electricians, construction workers and general trades. On residential rewires and commercial fit-outs, the combined jaws let technicians cut, strip and crimp in one pass, reducing the trips back to the tool bag that slow down panel and junction-box work. For maintenance crews servicing machinery and conveyors, the hardened edges stay sharp through daily use on copper, steel wire and light cable, while the TPR grip keeps hands comfortable during long overhead sessions.",
        "specs": [
            ("Material", "Chrome Vanadium Steel, Drop Forged"),
            ("Length", "6 inch (8/9 inch available)"),
            ("Type", "Lineman / Combination Pliers"),
            ("Functions", "Cutting, Gripping, Crimping"),
            ("Handle", "TPR Comfort Grip"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Drop-forged CR-V steel - strong & durable",
            "Induction-hardened cutting edges",
            "Multi-function: cut, grip, crimp, strip",
            "Crimp and strip wire without extra tools",
            "Comfort grip reduces hand fatigue",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "magnetic-screwdriver-set", "pneumatic-air-nailer"],
    },
    {
        "slug": "brushless-cordless-drill",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Drill Kit (2 Batteries + Charger)",
        "badge": "Hot",
        "price": "$11.00 - $16.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-cordless-drill.jpg",
        "src": "https://detail.1688.com/offer/806889479426.html",
        "desc": "Powerful 21V brushless cordless drill delivering high efficiency and longer runtime than brushed motors. The variable-speed trigger, keyless chuck and LED work light make drilling and screw-driving fast and accurate in any job site condition. This complete kit includes two lithium batteries, a fast charger and a durable plastic case, ready for export. Excellent for carpenters, electricians, furniture assembly teams and DIY enthusiasts. On assembly lines and renovation sites, the two-battery kit keeps drilling moving while one pack charges, and the keyless chuck makes bit changes quick between pilot holes and screw-driving. For electricians and furniture teams, the variable-speed trigger and LED work light give clean control in cabinets, roof voids and dark corners. For crews building a cordless system, this drill pairs with a compact 21V impact driver on the same battery platform to handle both drilling and fastening across the job.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Kit Includes", "2 Batteries + Charger + Case"),
            ("Chuck", "Keyless"),
            ("Plug Standard", "EU / US (on request)"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "Brushless motor - more power, longer life",
            "Complete kit: 2 batteries + charger + case",
            "Variable speed & keyless chuck",
            "Ready for export with plug options",
            "LED work light brightens dark corners & cabinets",
        ],
        "related": ["brushless-cordless-angle-grinder", "brushless-impact-wrench", "magnetic-screwdriver-set"],
    },
    {
        "slug": "brushless-cordless-angle-grinder",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Angle Grinder 4.5\"",
        "badge": "New",
        "price": "$26.00 - $38.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-cordless-angle-grinder.jpg",
        "src": "https://detail.1688.com/offer/919795260450.html",
        "desc": "Versatile brushless cordless angle grinder with a rotating head for cutting, grinding, polishing and rust removal in hard-to-reach positions. The 21V brushless motor delivers consistent power with up to 7.5Ah battery capacity for extended working time. Features include tool-free guard adjustment, side handle for control and spindle lock for fast disc changes. Ideal for metalwork, construction, tile work and maintenance crews who need cordless freedom. The rotating head lets operators cut and grind flush against surfaces fixed-head grinders cannot reach, such as door frames, chassis rails and confined ductwork. Maintenance crews switch between grinding disc and polishing pad in seconds using the spindle lock, keeping changeover time to a minimum on the job.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Disc Size", "100 mm / 4.5 inch"),
            ("Battery", "Up to 7.5 Ah (kit option)"),
            ("Head", "3-Axis Rotating"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "Rotating head reaches awkward angles",
            "Brushless motor with up to 7.5Ah runtime",
            "Cutting, grinding, polishing & rust removal",
            "Tool-free guard & spindle lock",
            "Shares the 21V Li-ion platform across the cordless range",
        ],
        "related": ["brushless-cordless-drill", "brushless-impact-wrench", "hvlp-gravity-spray-gun"],
    },
    {
        "slug": "brushless-impact-wrench",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Impact Wrench (Model 285)",
        "badge": "Bestseller",
        "price": "$15.00 - $22.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-impact-wrench.jpg",
        "src": "https://detail.1688.com/offer/842431375043.html",
        "desc": "High-torque brushless cordless impact wrench purpose-built for automotive repair, scaffolding and construction fastening. The 21V brushless motor delivers rapid-impact torque to remove stubborn lug nuts and bolts, while the compact body fits tight engine bays. This export kit includes two 10-cell batteries and a fast charger. A dependable workhorse for mechanics, tire shops and field service teams. As cordless impact wrenches become the standard on professional job sites, this high-torque model delivers the removal power crews expect without needing an air compressor nearby. For tire shops rotating seasonal wheels and field service teams working roadside, the cordless design removes the need for a compressor and hose, while the included twin-battery kit keeps the wrench running through a full day of lug-nut work.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Drive", "1/2 inch Square"),
            ("Battery", "2 × 10-Cell Li-ion"),
            ("Application", "Auto Repair, Scaffolding, Construction"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "High-torque impact for stubborn fasteners",
            "Brushless motor - longer runtime & life",
            "1/2\" drive fits standard sockets",
            "Export kit with 2 batteries + charger",
            "Compact body fits tight engine bays & scaffolding joints",
        ],
        "related": ["brushless-cordless-drill", "brushless-cordless-angle-grinder", "air-impact-wrench"],
    },
    {
        "slug": "air-impact-wrench",
        "cat": "pneumatic-tools",
        "name": "1/2\" Heavy Duty Air Impact Wrench (Pistol Grip)",
        "badge": "Hot",
        "price": "$30.00 - $44.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/air-impact-wrench.jpg",
        "src": "https://detail.1688.com/offer/683522828976.html",
        "desc": "Industrial-grade pneumatic impact wrench with high torque output for automotive tire service, machinery maintenance and heavy assembly work. The pistol-grip body is precision-balanced for comfortable control, and the twin-hammer mechanism delivers reliable, repeatable impact force. Built with a durable aluminum housing and ergonomic rubber grip, this tool connects to any standard air compressor for long, maintenance-free service. A cost-effective choice for garages and workshops worldwide. Tire shops and fleet garages rely on the twin-hammer impact for fast wheel changes during peak service hours, while machinery maintenance teams use the 1/2-inch drive with standard sockets to break loose corroded bolts on pumps and gearboxes. Because it runs on shop air, there are no batteries to recharge or motors to overheat, keeping cost per job low in high-volume workshops.",
        "specs": [
            ("Drive", "1/2 inch"),
            ("Type", "Pistol Grip Impact Wrench"),
            ("Body", "Aluminum Housing"),
            ("Mechanism", "Twin-Hammer"),
            ("Application", "Auto Repair, Tire Service, Industry"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "High torque for lug nuts & bolts",
            "Twin-hammer mechanism - reliable power",
            "Lightweight aluminum body, ergonomic grip",
            "Works with standard air compressors",
            "Standard 1/2 inch drive fits existing sockets",
        ],
        "related": ["pneumatic-air-nailer", "hvlp-gravity-spray-gun", "brushless-impact-wrench"],
    },
    {
        "slug": "pneumatic-air-nailer",
        "cat": "pneumatic-tools",
        "name": "Pneumatic Straight Nail Gun (F30 / 30mm)",
        "badge": "Bestseller",
        "price": "$6.00 - $9.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/pneumatic-air-nailer.jpg",
        "src": "https://detail.1688.com/offer/570819195363.html",
        "desc": "Reliable pneumatic straight nailer designed for cabinet making, furniture assembly, trim work and general woodworking. Fires 30mm F-type finish nails with consistent depth control, and the anti-jam magazine keeps production moving. The lightweight aluminum body and comfortable grip reduce operator fatigue during long shifts. Connects to any standard air compressor with a quick-connect fitting. A practical addition to any workshop or production line. Cabinet shops and furniture factories use the F30 nailer for face frames, drawer boxes and trim, where consistent depth control reduces sanding and touch-up work. For installers fitting baseboards and crown molding, the anti-jam magazine and quick-connect air fitting keep the tool feeding smoothly through long finishing runs.",
        "specs": [
            ("Fastener", "F30 Straight Nails (30 mm)"),
            ("Magazine", "Anti-Jam Design"),
            ("Body", "Lightweight Aluminum"),
            ("Application", "Woodworking, Furniture, Trim"),
            ("Air Supply", "Standard Compressor"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Anti-jam magazine for non-stop work",
            "30mm F-type finish nails",
            "Lightweight - reduces fatigue",
            "Perfect for furniture & woodworking",
            "Consistent depth control cuts sanding & touch-up work",
        ],
        "related": ["air-impact-wrench", "hvlp-gravity-spray-gun", "industrial-lineman-pliers"],
    },
    {
        "slug": "hvlp-gravity-spray-gun",
        "cat": "pneumatic-tools",
        "name": "HVLP Gravity Spray Gun 1.4mm Nozzle (H827)",
        "badge": "Hot",
        "price": "$5.00 - $7.50 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/hvlp-gravity-spray-gun.jpg",
        "src": "https://detail.1688.com/offer/653316938139.html",
        "desc": "Professional HVLP gravity-feed spray gun delivering fine, even atomization for automotive topcoats, primers, furniture finishes and industrial coatings. The 1.4mm nozzle balances flow rate and finish quality for both base and clear coats. Anodized aluminum body with stainless steel needle and nozzle ensures corrosion resistance and easy cleaning. Precise air and fluid controls give painters full command over pattern width and material delivery. Excellent value for body shops and finishing workshops.",
        "specs": [
            ("Type", "HVLP Gravity Feed"),
            ("Nozzle", "1.4 mm"),
            ("Cup", "600 ml Top Cup Included"),
            ("Body", "Anodized Aluminum"),
            ("Application", "Auto Paint, Primer, Furniture Finish"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Fine atomization - smooth professional finish",
            "1.4mm nozzle suits base & clear coats",
            "Stainless needle & nozzle - easy clean",
            "Precise air & fluid adjustment controls",
            "600ml top cup - fewer refills mid-job",
        ],
        "related": ["pneumatic-air-nailer", "air-impact-wrench", "brushless-cordless-angle-grinder"],
    },
    {
        "slug": "loose-pin-door-hinge",
        "cat": "hardware",
        "name": "304 Stainless Steel Loose-Pin Door Hinge (25mm Pin)",
        "badge": "New",
        "price": "$0.14 - $0.20 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/loose-pin-door-hinge.jpg",
        "src": "https://detail.1688.com/offer/591870381566.html",
        "desc": "Heavy-duty loose-pin door hinge machined from 304 stainless steel with a solid 25mm steel-core pin. The detachable pin design lets the door lift off the frame in seconds for quick installation, cleaning or replacement, while the two interlocking barrels keep the door perfectly aligned under heavy daily use. Ideal for wooden doors, gates, workshop furniture and renovation projects, this hinge suits both indoor and outdoor applications thanks to its corrosion-resistant brushed finish. Factory-direct supply supports custom sizes, bulk packaging and OEM finishing for hardware distributors, furniture makers and construction suppliers worldwide. For importers and distributors, its fast-moving price point, compact packaging and custom-size capability make it an easy add-on SKU for door hardware ranges serving fencing, barn doors and outdoor utility builds. With door hardware brands refreshing their lever, knob and hinge lines for the 2026 remodel season, this hinge lets distributors pair matching pulls and stops to build complete residential door sets from a single order.",
        "specs": [
            ("Material", "304 Stainless Steel"),
            ("Type", "Loose-Pin Flag Hinge"),
            ("Pin", "25 mm Steel Core"),
            ("Finish", "Brushed"),
            ("Application", "Wooden Door, Gate, Furniture"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Detachable pin - door lifts off in seconds",
            "304 stainless steel - rust resistant outdoors",
            "Solid 25mm pin keeps alignment under heavy use",
            "Factory-direct with custom sizes & finishing",
            "Easy add-on SKU for door hardware ranges - high turnover",
            "Interlocking barrels keep door aligned under heavy daily use",
        ],
        "related": ["stainless-steel-soft-close-hinge", "360-degree-pivot-door-hinge", "black-aluminum-cabinet-handle"],
    },
    {
        "slug": "360-degree-pivot-door-hinge",
        "cat": "hardware",
        "name": "360° Stainless Steel Pivot Door Hinge (Concealed)",
        "badge": "New",
        "price": "$0.17 - $0.25 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/360-degree-pivot-door-hinge.jpg",
        "src": "https://detail.1688.com/offer/809486914272.html",
        "desc": "Concealed pivot hinge offering full 360-degree rotation for doors that must open flat against the wall or swing in tight spaces. Each plate is precision-stamped from 304 stainless steel at 1.6mm thickness with four countersunk mounting holes for a secure, flush fit. The compact 59 x 11mm profile disappears into the door edge, creating an invisible mounting point that suits modern minimalist interiors, wardrobe doors, partition panels and light commercial partitions. Sold individually, factory-direct with consistent quality for furniture makers and renovation contractors. Its low cost and space-saving design make it a strong complementary line for hardware retailers and e-commerce sellers stocking modern door fittings.",
        "specs": [
            ("Material", "304 Stainless Steel"),
            ("Rotation", "360 Degrees"),
            ("Plate Size", "59 x 11 mm"),
            ("Thickness", "1.6 mm"),
            ("Weight", "Approx. 30.5 g"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Full 360° rotation - opens flat against the wall",
            "1.6mm stainless steel plates, flush concealed fit",
            "Compact profile for minimalist door designs",
            "Four countersunk holes for secure mounting",
            "Low-cost space-saver - a natural add-on for modern door fitting ranges",
            "Weighs only ~30.5g - quick, easy installation",
        ],
        "related": ["stainless-steel-soft-close-hinge", "loose-pin-door-hinge", "heavy-duty-swivel-caster"],
    },
    {
        "slug": "cabinet-hinge-repair-plate",
        "cat": "hardware",
        "name": "Stainless Steel Cabinet Hinge Repair Plate (90mm)",
        "badge": "Hot",
        "price": "$0.04 - $0.06 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/cabinet-hinge-repair-plate.jpg",
        "src": "https://detail.1688.com/offer/726416184167.html",
        "desc": "Practical hinge repair plate that restores stripped or broken cabinet hinge holes in minutes. The brushed stainless steel plate measures 90 x 47mm with a 35mm center opening and seven pre-drilled holes that accept both the original hinge screws and fresh screws into solid wood. Simply position the plate over the damaged area, mark the pilot holes and re-mount the hinge for a rock-solid fix. Four self-tapping mounting screws are included. A low-cost, high-value accessory for cabinet makers, kitchen remodelers, property maintenance teams and furniture repair services. For retailers it is an ideal impulse-buy accessory that pairs with any hinge range and solves a common on-site problem for tradespeople.",
        "specs": [
            ("Material", "Stainless Steel"),
            ("Size", "90 x 47 mm"),
            ("Center Opening", "35 mm"),
            ("Holes", "7 Pre-Drilled"),
            ("Screws", "4 Mounting Screws Included"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Fixes stripped hinge holes in minutes",
            "90mm stainless plate - strong & rust resistant",
            "7 pre-drilled holes fit standard hinges",
            "Mounting screws included - ready to install",
            "Natural cross-sell accessory for any hinge range",
            "Brushed stainless finish blends with existing hinges",
        ],
        "related": ["stainless-steel-soft-close-hinge", "black-aluminum-cabinet-handle", "loose-pin-door-hinge"],
    },
    {
        "slug": "mini-ratchet-handle-set",
        "cat": "hand-tools",
        "name": "Mini Ratchet Handle 72-Tooth (1/4\" Drive, 90mm)",
        "badge": "New",
        "price": "$1.75 - $2.60 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/mini-ratchet-handle-set.jpg",
        "src": "https://detail.1688.com/offer/845847639056.html",
        "desc": "Compact mini ratchet handle built for fast work in tight spaces. The 72-tooth mechanism delivers a fine 5-degree swing arc, and the 1/4-inch (6.35mm) square drive accepts standard socket sets. A polished chrome-plated finish resists corrosion, while the knurled grip and quick-release button give confident one-handed control. At just 90mm long it slips into tool bags, gloveboxes and service kits with ease. A dependable addition for mechanics, electricians, plumbers and DIY users who need a pocket-sized ratchet that performs like a full-size tool. Light enough to bundle into socket sets and service kits, it gives distributors a high-margin pocket tool that complements full-size ratchet ranges.",
        "specs": [
            ("Drive", "1/4 inch (6.35 mm)"),
            ("Teeth", "72-Tooth Ratchet"),
            ("Length", "90 mm"),
            ("Material", "Chrome-Plated Steel"),
            ("Feature", "Quick-Release Button"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "72-tooth ratchet - works in tight spaces",
            "1/4\" drive fits standard sockets",
            "Knurled grip & quick-release button",
            "Pocket-size 90mm length for travel kits",
            "High-margin pocket tool that complements full-size ratchet ranges",
            "5-degree swing arc - fast work in confined areas",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "magnetic-screwdriver-set", "industrial-lineman-pliers"],
    },
    {
        "slug": "diagonal-cutting-pliers",
        "cat": "hand-tools",
        "name": "8\" Diagonal Cutting Pliers (CR-V Forged, 186mm)",
        "badge": "Hot",
        "price": "$1.05 - $1.60 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/diagonal-cutting-pliers.jpg",
        "src": "https://detail.1688.com/offer/1045273600137.html",
        "desc": "Industrial-grade diagonal cutting pliers drop-forged from chrome vanadium steel with induction-hardened cutting edges that slice through wire, cable, nails and thin metal with minimal effort. The precision-aligned joint keeps the jaws true under repeated heavy cuts, while the ergonomic two-tone TPR handles provide a comfortable, non-slip grip that reduces hand fatigue during long jobs. At 186mm overall length they balance leverage and control for electrical work, automotive repairs, construction and general maintenance. Ships in retail card packaging, ready for hardware shelves and export orders. With its card-pack display and mid-range price point, it is a dependable stock-keeping unit for hardware retailers, tool wholesalers and online sellers.",
        "specs": [
            ("Material", "Chrome Vanadium Steel, Drop Forged"),
            ("Length", "186 mm (8 inch)"),
            ("Head Thickness", "10 mm"),
            ("Weight", "287 g"),
            ("Handle", "TPR Anti-Slip Grip"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Drop-forged CR-V steel - strong & durable",
            "Induction-hardened edges for clean cuts",
            "Ergonomic TPR grip reduces fatigue",
            "Retail card pack ready for export",
            "Card-pack format - shelf-ready for hardware retail",
            "Cuts wire, cable, nails & thin metal with minimal effort",
        ],
        "related": ["industrial-lineman-pliers", "magnetic-screwdriver-set", "mini-ratchet-handle-set"],
    },
    {
        "slug": "brushless-impact-drill-kit",
        "cat": "power-tools",
        "name": "21V Brushless Impact Drill Kit (1 Battery + Charger)",
        "badge": "Bestseller",
        "price": "$7.30 - $11.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-impact-drill-kit.jpg",
        "src": "https://detail.1688.com/offer/998398397618.html",
         "desc": "Compact 21V brushless impact drill combining drilling and screw-driving power with a hammer-impact function for masonry work. The brushless motor delivers more torque and longer runtime than brushed designs, while the keyless chuck, variable-speed trigger and built-in LED work light keep the job moving in any light. A belt clip and ergonomic grip make it easy to carry around the site. This export kit includes one lithium battery, a fast charger and a storage box - a practical starter package for DIY users, electricians, carpenters and furniture assembly teams. With hammer-impact drilling and screw-driving in one brushless tool, it covers both impact driver and drill duties on the cordless battery platform, matching the way modern job sites search for and buy compact impact drivers. For importers, the brushless value story and complete kit format deliver a strong entry-level power-tool offer that encourages repeat battery-platform purchases.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Kit Includes", "1 Battery + Charger + Box"),
            ("Chuck", "Keyless"),
            ("Feature", "Impact Function, LED Light, Belt Clip"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "Brushless motor - more torque & runtime",
            "Impact function drills masonry & brick",
            "LED work light for dark job sites",
            "Ready-to-go kit with battery & charger",
            "Strong entry point into a cordless battery platform",
            "Keyless chuck & variable-speed trigger - full control",
        ],
        "related": ["brushless-cordless-drill", "brushless-impact-wrench", "magnetic-screwdriver-set"],
    },
    {
        "slug": "12v-cordless-drill",
        "cat": "power-tools",
        "name": "12V Compact Cordless Drill / Screwdriver",
        "badge": "New",
        "price": "$3.10 - $4.70 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/12v-cordless-drill.jpg",
        "src": "https://detail.1688.com/offer/1001413718249.html",
        "desc": "Lightweight 12V-class cordless drill engineered for precision fastening and light drilling. The compact teal body houses a two-speed gearbox, a 1-9 adjustable torque clutch that protects screw heads from over-driving, and a forward/reverse switch for quick bit changes. The keyless chuck accepts standard drill bits and screwdriver bits, making it ideal for furniture assembly, cabinet installation, electronics repair and everyday household tasks. Its slim grip and low weight reduce fatigue during extended use. Sold as a bare tool, allowing buyers to pair it with their existing battery platform. For hardware retailers and e-commerce sellers, the compact form factor and beginner-friendly controls make it a strong impulse add-on for first-time tool buyers, while the bare-tool format keeps stock flexible and matches customers who already own a 12V battery and charger.",
        "specs": [
            ("Voltage", "12 V Li-ion"),
            ("Chuck", "Keyless"),
            ("Speeds", "2-Speed Gearbox"),
            ("Torque", "1-9 Adjustable Clutch"),
            ("Type", "Drill / Screwdriver"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Compact & lightweight - less fatigue",
            "Two-speed gearbox with 1-9 torque clutch",
            "Keyless chuck accepts standard bits",
            "Bare tool pairs with existing battery systems",
            "Slim grip & low weight - comfortable all-day use",
        ],
        "related": ["brushless-cordless-drill", "brushless-impact-drill-kit", "magnetic-screwdriver-set"],
    },
    {
        "slug": "brushless-impact-wrench-kit",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Impact Wrench Kit (2 Batteries + 12 Accessories)",
        "badge": "Bestseller",
        "price": "$29.80 - $44.70 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-impact-wrench-kit.jpg",
        "src": "https://detail.1688.com/offer/887337380550.html",
        "desc": "High-torque 21V brushless cordless impact wrench built for automotive repair, tire service, scaffolding and construction fastening. The 1/2-inch square drive delivers rapid-impact torque to break loose stubborn lug nuts and bolts, while the compact body and rubberized grip give full control in tight bays. This complete export kit includes two lithium batteries, a US-standard charger, a hard plastic carrying case and 12 accessories covering six impact sockets, a drill chuck, screwdriver bits and adapters - everything a workshop needs out of the box. A dependable workhorse for mechanics, fleet maintenance and field service teams. For distributors, the all-in-one kit reduces accessory sourcing and after-sales friction, while the interchangeable battery platform encourages repeat purchases of bare tools and spare batteries across the same 21V line.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Drive", "1/2 inch Square"),
            ("Kit Includes", "2 Batteries + US Charger + Case + 12 Accessories"),
            ("Application", "Auto Repair, Tire Service, Construction"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "High-torque impact for stubborn fasteners",
            "Complete kit: 2 batteries + charger + case",
            "12 accessories cover common workshop jobs",
            "Compact body fits tight engine bays",
            "Rubberized grip - steady control in oily, tight spaces",
        ],
        "related": ["brushless-impact-wrench", "brushless-cordless-drill", "air-impact-wrench"],
    },
    {
        "slug": "mining-air-impact-wrench",
        "cat": "pneumatic-tools",
        "name": "Heavy-Duty Air Impact Wrench (1\" Drive, D-Handle)",
        "badge": "New",
        "price": "$33.80 - $50.70 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/mining-air-impact-wrench.jpg",
        "src": "https://detail.1688.com/offer/980434703079.html",
        "desc": "Industrial-grade pneumatic impact wrench with a 1-inch square drive and integrated D-handle, engineered for the highest-torque fastening jobs in mining, heavy machinery maintenance, truck tire service and plant assembly. The twin-hammer mechanism delivers powerful, repeatable impact force, while the rugged aluminum housing and cooling fins stand up to continuous workshop duty. A rear air inlet with regulator knob, detachable auxiliary handle, mounting bolts and air fitting are included for fast setup. Connects to any standard high-capacity air compressor for long, dependable service. For heavy-industry suppliers and equipment rental fleets, the 1-inch drive fills the gap where smaller wrenches stall, and the included mounting hardware cuts setup time on job sites, making it a high-value line item for mining, transport and plant maintenance contracts.",
        "specs": [
            ("Drive", "1 inch Square"),
            ("Type", "D-Handle Impact Wrench"),
            ("Body", "Aluminum Alloy with Cooling Fins"),
            ("Application", "Mining, Heavy Machinery, Truck Tire"),
            ("Includes", "Auxiliary Handle, Bolts, Air Fitting"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "1\" drive for maximum torque output",
            "Twin-hammer mechanism - reliable power",
            "D-handle & auxiliary handle for control",
            "Built for mining & heavy-duty service",
            "Includes auxiliary handle, bolts & air fitting - ready to run",
        ],
        "related": ["air-impact-wrench", "brushless-impact-wrench", "pneumatic-air-nailer"],
    },
    {
        "slug": "aluminum-siphon-spray-gun",
        "cat": "pneumatic-tools",
        "name": "Aluminum Siphon-Feed Spray Gun (1000ml, Undercoat & Rust-Proof)",
        "badge": "Hot",
        "price": "$6.40 - $9.60 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/aluminum-siphon-spray-gun.jpg",
        "src": "https://detail.1688.com/offer/984444367095.html",
        "desc": "Heavy-duty siphon-feed spray gun purpose-built for thick coatings such as automotive undercoating, rust-proofing, chassis protection and industrial paints. The 1000ml stainless steel canister feeds material through a brass adjustable nozzle, while the integrated pressure gauge and regulator give precise control over atomization and spray pattern. Two flexible extension tubes with brass spray tips reach into cavities, box sections and hard-to-access frames. The ergonomic pistol grip and heavy construction make long coating sessions comfortable. A practical choice for body shops, garages and maintenance crews. For tool suppliers and industrial distributors, the undercoating niche complements standard HVLP lines with minimal shelf overlap, and the 1000ml canister plus extension tubes give technicians a complete rust-protection setup from a single SKU.",
        "specs": [
            ("Type", "Siphon-Feed Pressure Canister"),
            ("Cup", "1000 ml Steel Canister"),
            ("Nozzle", "Brass Adjustable"),
            ("Includes", "Pressure Gauge + Regulator, 2 Extension Tubes"),
            ("Application", "Undercoat, Rust-Proof, Thick Coatings"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Siphon feed handles thick undercoat paints",
            "1000ml steel canister - less refilling",
            "Gauge + regulator for precise control",
            "Extension tubes reach hidden cavities",
            "Complete undercoat setup - gauge, regulator & tips included",
            "Brass adjustable nozzle for fine atomization",
        ],
        "related": ["hvlp-gravity-spray-gun", "pneumatic-air-nailer", "air-impact-wrench"],
    },
    {
        "slug": "soft-close-drawer-slide-45mm",
        "cat": "hardware",
        "name": "45mm Soft-Close Drawer Slide (3-Section, 16\" / 400mm)",
        "badge": "New",
        "price": "$1.70 - $2.60 /pair",
        "moq": "MOQ 1 pair",
        "img": "/images/soft-close-drawer-slide-45mm.jpg",
        "src": "https://detail.1688.com/offer/794191407722.html",
        "desc": "Three-section ball-bearing drawer slide with a built-in damping buffer that closes drawers softly and quietly every time. The 45mm-wide cold-rolled steel rails are hardened for a 45kg load rating, and the detachable design lets you install the drawer and cabinet members separately for simple alignment. Side-mounted with pre-drilled oval and round mounting holes, it fits standard 16-inch (400mm) cabinet openings and works well for kitchen cabinets, wardrobes, dressers and office desks. The corrosion-resistant finish keeps the action smooth in humid environments, and the self-closing cushion protects both the hardware and the drawer front from slamming. A dependable choice for furniture makers, cabinet shops and renovation projects that need smooth, quiet drawers at a factory-direct price. Soft-close drawer slides remain a defining 2026 kitchen trend because they cut slamming noise, protect the cabinet box and give every drawer a refined, high-end feel - benefits this slide delivers at an accessible price point.",
        "specs": [
            ("Width", "45 mm"),
            ("Length", "400 mm (16 inch)"),
            ("Load Capacity", "45 kg"),
            ("Material", "Cold-Rolled Steel"),
            ("Type", "3-Section Detachable, Soft-Close Damping"),
            ("Mounting", "Side-Mounted"),
        ],
        "points": [
            "Built-in damping buffer - quiet, soft close",
            "45kg load rating for heavy drawers",
            "Detachable rails for easy installation",
            "Corrosion-resistant, smooth ball bearings",
            "Self-closing cushion protects drawer fronts",
        ],
        "related": ["black-aluminum-cabinet-handle", "stainless-steel-soft-close-hinge", "cabinet-hinge-repair-plate"],
    },
    {
        "slug": "no-drill-magnetic-door-stop",
        "cat": "hardware",
        "name": "No-Drill Magnetic Door Stop (Black, Strong Suction)",
        "badge": "Hot",
        "price": "$0.50 - $0.75 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/no-drill-magnetic-door-stop.jpg",
        "src": "https://detail.1688.com/offer/910585852991.html",
        "desc": "Slim two-piece magnetic door stop that holds doors open without drilling into walls or floors. The compact black floor plate houses a strong magnet, while the matching door bracket attaches to the bottom edge of the door - when the door swings open, the two halves click together and keep it firmly in place until you pull it free. The low-profile design suits modern interiors and works on wooden, metal and hollow doors in bedrooms, bathrooms, kitchens and utility rooms. Because there is no wall anchor, it also protects plaster and tile from damage and makes rental-friendly installation possible. A practical, low-cost upgrade for homeowners, property managers and hardware retailers building door hardware ranges. A consistent fast-mover in hardware retail hot-product roundups, the no-drill door stop is a compact, high-margin add-on that pairs naturally with hinges and handles in any door hardware assortment.",
        "specs": [
            ("Type", "Magnetic Floor Door Stop"),
            ("Installation", "No-Drill (Adhesive/Stick-On)"),
            ("Color", "Black"),
            ("Material", "Zinc Alloy / ABS"),
            ("Suction", "Strong Built-In Magnet"),
            ("Application", "Home Doors, Bedroom, Bathroom"),
        ],
        "points": [
            "No drilling - protects walls and floors",
            "Strong magnet holds doors firmly open",
            "Slim low-profile design for modern homes",
            "Works on wood, metal and hollow doors",
            "Protects plaster and tile from damage",
        ],
        "related": ["stainless-steel-soft-close-hinge", "360-degree-pivot-door-hinge", "magnetic-glass-door-catch"],
    },
    {
        "slug": "magnetic-glass-door-catch",
        "cat": "hardware",
        "name": "Magnetic Glass Door Catch (Brushed Silver)",
        "badge": "New",
        "price": "$0.90 - $1.35 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/magnetic-glass-door-catch.jpg",
        "src": "https://detail.1688.com/offer/572969467412.html",
        "desc": "Strong magnetic catch designed for glass partition doors and office glass doors. The brushed-silver housing holds a recessed circular magnet that locks cleanly onto the matching strike plate, while the U-shaped clamp bracket fits over the edge of a 10-12mm glass pane with a protective lining that prevents scratching. Two hex screws on the bracket secure the grip on the glass, and the set screw on the base fixes the magnet position. The result is a quiet, positive hold that keeps glass doors closed or open exactly where you want them, without visible floor hardware. Ideal for office partitions, conference rooms, showrooms and modern interiors where clean lines matter. For hardware importers, it is an easy add-on SKU for glass door fitting lines, and the clamp-on design removes the need for glass drilling that scares off many buyers.",
        "specs": [
            ("Material", "Zinc Alloy, Brushed Silver Finish"),
            ("Type", "Magnetic Catch for Glass Doors"),
            ("Installation", "Clamp-On U-Bracket (10-12mm Glass)"),
            ("Magnet", "Recessed Circular Magnet"),
            ("Fasteners", "Hex Screws Included"),
            ("Application", "Office Partitions, Glass Doors"),
        ],
        "points": [
            "Clamps onto glass - no drilling required",
            "Recessed magnet gives a clean, positive hold",
            "Protective lining prevents glass scratching",
            "Brushed silver finish matches modern interiors",
            "Easy add-on SKU for glass door hardware ranges",
            "Fits 10-12mm glass panes with secure hex-screw grip",
        ],
        "related": ["no-drill-magnetic-door-stop", "stainless-steel-soft-close-hinge", "heavy-duty-swivel-caster"],
    },
    {
        "slug": "rubber-grip-adjustable-wrench",
        "cat": "hand-tools",
        "name": "8\" Rubber-Grip Adjustable Wrench (207mm, Industrial Grade)",
        "badge": "New",
        "price": "$2.10 - $3.10 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/rubber-grip-adjustable-wrench.jpg",
        "src": "https://detail.1688.com/offer/804853031408.html",
        "desc": "Industrial-grade adjustable wrench with a smooth plastic-dipped green grip for comfortable, slip-resistant control. The polished head opens up to 20mm to handle a wide range of nuts, bolts and fittings, and the knurled worm gear adjusts the jaw quickly with one hand. A laser-etched millimeter scale on the fixed jaw lets you set the opening precisely before you reach into the workspace. At 207mm overall, it balances leverage and portability for plumbers, electricians, mechanics and general maintenance work. The hanging hole at the end of the handle keeps it easy to store on a pegboard or tool wall. A dependable everyday wrench for professionals and DIY users alike. For retailers, it fills the mid-price adjustable-wrench slot that complements socket sets in any hand-tool range, and the industrial finish supports strong repeat sales.",
        "specs": [
            ("Length", "207 mm (8 inch)"),
            ("Max Opening", "20 mm"),
            ("Head Width", "57 mm"),
            ("Opening Depth", "25 mm"),
            ("Weight", "0.28 kg"),
            ("Handle", "Plastic-Dipped Green Grip"),
        ],
        "points": [
            "Industrial grade - built for daily use",
            "Laser-etched scale for precise jaw setting",
            "Comfortable plastic-dipped grip",
            "One-hand knurled worm gear adjustment",
            "Fills the mid-price slot in any adjustable wrench range",
            "Hanging hole for pegboard and tool-wall storage",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "mini-ratchet-handle-set", "diagonal-cutting-pliers"],
    },
    {
        "slug": "heavy-duty-tape-measure-5m",
        "cat": "hand-tools",
        "name": "Heavy-Duty Tape Measure 5m / 16ft (25mm, Auto-Lock)",
        "badge": "Hot",
        "price": "$0.66 - $1.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/heavy-duty-tape-measure-5m.jpg",
        "src": "https://detail.1688.com/offer/853820054159.html",
        "desc": "Tough 5-meter tape measure built for jobsite abuse, with a shock-resistant matte black casing and textured rubber grip. The 25mm-wide steel blade carries clear dual metric and imperial markings, so you can measure quickly whether your project uses millimeters or feet. A thumb-operated auto-lock slide locks the blade in place automatically for one-handed measuring, then releases it smoothly when you press the lock. The rugged housing absorbs drops, and the riveted end hook grips workpieces securely for accurate inside and outside measurements. Ideal for carpenters, electricians, plumbers, contractors and DIY users who need a reliable everyday tape that can take a beating. With its dual-scale blade and low price point, it is a dependable stock-keeping unit for hardware stores, tool wholesalers and e-commerce sellers building daily-use hand-tool assortments.",
        "specs": [
            ("Length", "5 m / 16 ft"),
            ("Tape Width", "25 mm"),
            ("Lock", "Auto-Lock Thumb Slide"),
            ("Casing", "Impact-Resistant ABS, Matte Black"),
            ("Scale", "Dual Metric / Imperial"),
            ("Hook", "Riveted Steel End Hook"),
        ],
        "points": [
            "Auto-lock for one-handed measuring",
            "Dual metric/imperial markings",
            "Impact-resistant rubberized casing",
            "25mm wide blade for stable readings",
            "Dependable daily-use SKU for hand-tool assortments",
            "Riveted end hook for accurate inside & outside readings",
        ],
        "related": ["magnetic-screwdriver-set", "72-tooth-ratchet-wrench-set", "industrial-lineman-pliers"],
    },
    {
        "slug": "5-inch-brushless-circular-saw-kit",
        "cat": "power-tools",
        "name": "5\" Brushless Cordless Circular Saw Kit (1 Battery + Charger)",
        "badge": "Bestseller",
        "price": "$14.50 - $21.80 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/5-inch-brushless-circular-saw-kit.jpg",
        "src": "https://detail.1688.com/offer/899787273104.html",
        "desc": "Compact one-hand circular saw powered by a brushless motor for longer runtime and steadier cutting power. The 5-inch blade handles wood, plywood, boards and light sheet material, with an adjustable base that sets cutting depth and tilts up to 45 degrees for bevel cuts. The ergonomic body with rubberized grip and trigger makes single-hand operation comfortable, and the metal blade guard adds safety on the jobsite. This export kit includes the saw, one 10-cell lithium battery, a fast charger with US plug and the adjustment wrenches - everything needed to start cutting right away. A practical entry-level saw for carpenters, joiners, DIY remodelers and property maintenance teams. For distributors, the brushless motor story and complete kit format make it a strong entry offer that introduces buyers to a shared battery platform for future tool sales. As brushless cordless circular saws dominate 2026 tool round-ups for runtime and cutting consistency, this one-hand model brings that performance to a compact, affordable format.",
        "specs": [
            ("Blade", "5 inch"),
            ("Motor", "Brushless"),
            ("Cutting", "Depth Adjustable, 0-45° Bevel"),
            ("Kit Includes", "Saw + 1 Battery + Charger + Wrenches"),
            ("Battery", "10-Cell Li-ion, US Plug Charger"),
            ("Design", "Compact One-Hand Grip"),
        ],
        "points": [
            "Brushless motor - longer runtime, more power",
            "One-hand compact design for tight spots",
            "0-45° bevel cuts with adjustable depth",
            "Complete kit - battery and charger included",
            "Strong entry offer into a shared battery platform",
            "Metal blade guard adds jobsite safety",
        ],
        "related": ["brushless-cordless-drill", "brushless-cordless-angle-grinder", "brushless-impact-wrench"],
    },
    {
        "slug": "brushless-cordless-rotary-hammer",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Rotary Hammer (2 Batteries, SDS-Plus)",
        "badge": "New",
        "price": "$20.30 - $30.40 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-cordless-rotary-hammer.jpg",
        "src": "https://detail.1688.com/offer/917773475812.html",
        "desc": "Cordless rotary hammer that drills, hammers and chisels through concrete, brick and masonry without dragging an extension cord around. The brushless motor delivers strong impact energy for anchor holes, and the SDS-Plus chuck swaps bits quickly without a key. A three-mode selector dial switches between drilling, hammer drilling and chiseling, while the variable-speed trigger and auxiliary handle give you control on vertical and overhead work. This kit ships with two lithium batteries, a fast charger and a hard carrying case, plus a depth gauge for consistent hole depths. A practical choice for electricians, plumbers, HVAC fitters and renovation crews who move between rooms and floors. For importers, the cordless convenience and two-battery runtime give it a clear selling story against corded hammers, supporting healthy margins in concrete-tool ranges.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Chuck", "SDS-Plus"),
            ("Modes", "Drill / Hammer / Chisel"),
            ("Kit Includes", "2 Batteries + Charger + Case + Depth Gauge"),
            ("Battery", "20000mAh-Class"),
        ],
        "points": [
            "Three modes - drill, hammer, chisel",
            "SDS-Plus chuck - keyless bit changes",
            "Two batteries for continuous work",
            "Hard case included for transport",
            "Cordless convenience - a clear upgrade story over corded hammers",
            "Depth gauge keeps anchor holes consistent",
        ],
        "related": ["brushless-cordless-drill", "brushless-impact-drill-kit", "corded-impact-drill-13mm"],
    },
    {
        "slug": "corded-impact-drill-13mm",
        "cat": "power-tools",
        "name": "13mm Corded Impact Drill (Industrial Grade, Standard Kit)",
        "badge": "Bestseller",
        "price": "$5.10 - $7.60 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/corded-impact-drill-13mm.jpg",
        "src": "https://detail.1688.com/offer/1051607910607.html",
        "desc": "Budget-friendly corded impact drill that brings hammer action to concrete drilling for home and light commercial use. The 13mm keyed chuck grips twist bits and masonry bits securely, while the impact mechanism breaks through brick and concrete block for anchors and shelf fixings. A variable-speed trigger and forward/reverse switch give control for drilling and screw driving, and the side handle with depth gauge helps you keep holes straight and consistent. This standard kit includes the drill, auxiliary handle, chuck key and depth rod. The EU-plug power cord means no battery charging - just plug in and work. A dependable starter drill for DIY users, maintenance staff and rental tool fleets. Its low cost and plug-and-work simplicity make it an attractive entry product for budget-conscious buyers and a practical add-on for hardware retail shelves.",
        "specs": [
            ("Chuck", "13 mm Keyed"),
            ("Power", "Corded, EU Plug"),
            ("Motor", "Brushed"),
            ("Features", "Impact + Drill Modes, Variable Speed"),
            ("Kit Includes", "Auxiliary Handle, Chuck Key, Depth Gauge"),
            ("Application", "Concrete, Wood, Metal"),
        ],
        "points": [
            "Hammer action drills into concrete",
            "13mm keyed chuck - secure bit grip",
            "Side handle with depth gauge included",
            "No battery needed - plug and work",
            "Plug-and-work simplicity - a budget-friendly entry product",
            "Forward/reverse switch for drilling & screw driving",
        ],
        "related": ["brushless-cordless-drill", "12v-cordless-drill", "brushless-impact-drill-kit"],
    },
    {
        "slug": "rectangular-air-sander",
        "cat": "pneumatic-tools",
        "name": "Rectangular Air Sander (75×100mm, Orbital Palm)",
        "badge": "Hot",
        "price": "$7.90 - $11.80 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/rectangular-air-sander.jpg",
        "src": "https://detail.1688.com/offer/994452404165.html",
        "desc": "Air-powered orbital palm sander with a rectangular 75x100mm pad that reaches flat panels and tight corners with ease. The long chrome trigger lever gives precise airflow control, and the palm-shaped red grip keeps the tool stable in your hand for extended sanding sessions. The hook-and-loop pad accepts standard rectangular sandpaper sheets, making changeovers fast on bodywork, furniture and wood finishing jobs. A small airflow lever on the rear adjusts speed to match the material, and the quick-connect air inlet fits standard compressor fittings. Remember to oil the tool daily for smooth operation. A practical addition for auto body shops, furniture workshops and painters. For distributors, the rectangular pad and hook-and-loop convenience make it a high-value companion to air spray guns and compressors in any pneumatics range.",
        "specs": [
            ("Pad", "75 × 100 mm Rectangular"),
            ("Type", "Orbital Palm Sander"),
            ("Operation", "Air-Powered"),
            ("Grip", "Red Palm Grip"),
            ("Regulator", "Air Flow Lever"),
            ("Application", "Auto Body, Furniture, Wood"),
        ],
        "points": [
            "Rectangular pad covers flat panels fully",
            "Hook-and-loop pad - fast sandpaper changes",
            "Chrome trigger for precise air control",
            "Adjustable airflow for different materials",
            "High-value companion to air spray guns and compressors",
            "Quick-connect inlet fits standard compressor fittings",
        ],
        "related": ["aluminum-siphon-spray-gun", "hvlp-gravity-spray-gun", "air-impact-wrench"],
    },
    {
        "slug": "high-pressure-air-blow-gun",
        "cat": "pneumatic-tools",
        "name": "High-Pressure Air Blow Gun (Heavy-Duty, Quick-Connect)",
        "badge": "New",
        "price": "$0.80 - $1.20 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/high-pressure-air-blow-gun.jpg",
        "src": "https://detail.1688.com/offer/833936063132.html",
        "desc": "High-pressure air blow gun for fast, effective dust and debris cleaning around the workshop. The tapered nozzle concentrates airflow to blow dust out of machinery, electronics, workbenches, car interiors and hard-to-reach crevices, while the ergonomic contoured handle and curved trigger stay comfortable during repeated use. The quick-connect air inlet fits standard compressor hoses, and the reinforced composite body is lightweight yet drop-resistant for daily jobsite handling. A useful accessory for mechanics, woodworkers, CNC operators and anyone who keeps a compressor on hand. Pair it with an air hose and regulator for a complete cleaning setup. For suppliers, its low cost and universal quick-connect make it an easy bundle item with air hoses, fittings and compressors - a natural margin builder for pneumatic tool ranges.",
        "specs": [
            ("Type", "Air Blow Gun"),
            ("Inlet", "Quick-Connect Fitting"),
            ("Nozzle", "Tapered High-Flow"),
            ("Body", "Matte Black Composite"),
            ("Trigger", "Ergonomic Curved"),
            ("Application", "Dust Cleaning, Workshop, Compressor"),
        ],
        "points": [
            "High-pressure airflow for fast cleaning",
            "Lightweight and drop-resistant body",
            "Quick-connect fits standard hoses",
            "Comfortable grip for repeated use",
            "Natural bundle item with hoses and compressors",
            "Tapered nozzle clears hard-to-reach crevices",
        ],
        "related": ["air-impact-wrench", "rectangular-air-sander", "pneumatic-air-nailer"],
    },
    {
        "slug": "stainless-corner-brace-40mm",
        "cat": "hardware",
        "name": "Stainless Steel Corner Brace 40x40mm (10-Pack)",
        "badge": "New",
        "price": "$0.40 - $0.65 /pack",
        "moq": "MOQ 1 pack",
        "img": "/images/stainless-corner-brace-40mm.jpg",
        "src": "https://detail.1688.com/offer/672195950792.html",
        "desc": "Rugged L-shaped corner brace machined from brushed stainless steel for strong right-angle reinforcement on furniture, cabinets, frames, shelves and workbenches. Each arm measures 40 x 40mm with four countersunk 5mm holes that sit flush for a clean, professional fastening, and the rounded ends prevent snagging during handling. The corrosion-resistant finish stands up to kitchens, workshops and outdoor furniture where moisture and wear are a daily reality. This value pack contains ten braces plus mounting screws, giving cabinet makers, furniture manufacturers, RV builders and DIY renovators a ready stock for production runs and repair jobs. A practical add-on SKU for hardware distributors looking to round out their fastening and bracket range.",
        "specs": [
            ("Size", "40 x 40 mm"),
            ("Thickness", "Approx. 1.8 mm"),
            ("Material", "Stainless Steel"),
            ("Holes", "4 Countersunk, 5 mm"),
            ("Finish", "Brushed"),
            ("Pack", "10 Pieces + Screws"),
        ],
        "points": [
            "Brushed stainless steel - corrosion resistant",
            "40x40mm arms with 4 flush countersunk holes",
            "Value pack of 10 with screws included",
            "Ready stock for cabinet & furniture production",
        ],
        "related": ["cabinet-hinge-repair-plate", "black-aluminum-cabinet-handle", "heavy-duty-swivel-caster"],
    },
    {
        "slug": "no-drill-heavy-duty-shelf-bracket",
        "cat": "hardware",
        "name": "No-Drill Heavy-Duty Shelf Bracket (Adhesive, Pack of 4)",
        "badge": "Hot",
        "price": "$0.30 - $0.45 /pack",
        "moq": "MOQ 1 pack",
        "img": "/images/no-drill-heavy-duty-shelf-bracket.jpg",
        "src": "https://detail.1688.com/offer/930560581089.html",
        "desc": "No-drill shelf bracket that mounts in seconds with its large adhesive sheet - no screws, no drill, no damage to cabinet walls. The reinforced ribbed design supports shelves under real weight while staying fully removable and reusable when you rearrange storage. Each enlarged, thickened bracket is molded with an anti-slip surface so the shelf sits stable, and the transparent body blends invisibly with any interior. Perfect for wardrobes, kitchen cabinets, pantries, bookcases and rental apartments where drilling is not an option. The pack of four covers a full shelf setup, and the seller backs the no-drill claim with a replacement guarantee. A fast-selling accessory for home organization and storage hardware ranges.",
        "specs": [
            ("Type", "Adhesive No-Drill"),
            ("Pack", "4 Pieces"),
            ("Material", "Reinforced ABS"),
            ("Load", "Reinforced Rib Design"),
            ("Installation", "Peel-and-Stick"),
            ("Application", "Wardrobes, Cabinets, Shelving"),
        ],
        "points": [
            "No-drill adhesive mount - damage-free",
            "Reinforced ribbed design for real shelf loads",
            "Transparent body blends into any interior",
            "Pack of 4 with replacement guarantee",
            "Removable & reusable - no wall damage",
        ],
        "related": ["soft-close-drawer-slide-45mm", "cabinet-hinge-repair-plate", "black-aluminum-cabinet-handle"],
    },
    {
        "slug": "adjustable-l-bracket-58mm",
        "cat": "hardware",
        "name": "Adjustable L-Bracket 58x58mm (Black, Double Slot)",
        "badge": "New",
        "price": "$0.08 - $0.13 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/adjustable-l-bracket-58mm.jpg",
        "src": "https://detail.1688.com/offer/829980202780.html",
        "desc": "Adjustable L-bracket with elongated 43mm slots on both arms, so you can position it precisely before tightening - ideal when hole centers never quite line up. Formed from cold-rolled steel at 2.7mm thick with a matte black finish, it delivers clean, low-profile reinforcement for shelving, frames, desks, gates and light structural joins. The 58 x 58mm footprint fits most corner applications, and the 6.7mm slots accept standard metric and imperial fasteners. At just 29.7g per piece, it ships economically in bulk and is a staple line for hardware wholesalers, furniture makers and e-commerce sellers building bracket assortments.",
        "specs": [
            ("Size", "58 x 58 mm"),
            ("Slot Length", "43 mm"),
            ("Slot Width", "6.7 mm"),
            ("Thickness", "2.7 mm"),
            ("Weight", "29.7 g"),
            ("Material", "Cold-Rolled Steel, Matte Black"),
        ],
        "points": [
            "Adjustable 43mm slots - perfect hole alignment",
            "2.7mm cold-rolled steel, matte black finish",
            "Lightweight - economic bulk shipping",
            "Staple SKU for bracket assortments",
            "Slots fit metric & imperial fasteners",
        ],
        "related": ["stainless-corner-brace-40mm", "no-drill-heavy-duty-shelf-bracket", "heavy-duty-swivel-caster"],
    },
    {
        "slug": "bakelite-grip-claw-hammer",
        "cat": "hand-tools",
        "name": "40cm Claw Hammer (0.5kg, Anti-Slip Bakelite Grip)",
        "badge": "New",
        "price": "$0.70 - $1.10 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/bakelite-grip-claw-hammer.jpg",
        "src": "https://detail.1688.com/offer/1045163672085.html",
        "desc": "Balanced claw hammer built for daily striking and nail pulling. The drop-forged steel head carries a waffled striking face that grips nail heads and reduces skidding, while the curved claw lever pulls stubborn nails cleanly without bending the handle. The 40cm anti-slip bakelite grip absorbs shock and stays comfortable even in cold or oily hands, and the 0.5kg head weight gives solid striking force without excessive fatigue. A dependable choice for carpenters, framers, electricians, furniture assemblers and DIY users who need one hammer for everyday work. Factory-direct supply supports bulk packing and OEM branding for tool wholesalers building hand-tool assortments.",
        "specs": [
            ("Head", "Drop-Forged Steel, Waffle Face"),
            ("Handle", "40 cm Anti-Slip Bakelite"),
            ("Weight", "0.5 kg"),
            ("Claw", "Curved Nail-Pulling"),
            ("Length", "40 cm"),
            ("Application", "Carpentry, Framing, DIY"),
        ],
        "points": [
            "Waffled face grips nail heads - less skidding",
            "Curved claw pulls nails cleanly",
            "Anti-slip bakelite grip absorbs shock",
            "0.5kg head - solid force without fatigue",
            "Drop-forged head - durable daily use",
        ],
        "related": ["diagonal-cutting-pliers", "rubber-grip-adjustable-wrench", "heavy-duty-tape-measure-5m"],
    },
    {
        "slug": "ball-end-hex-key-set-9pcs",
        "cat": "hand-tools",
        "name": "Ball-End Hex Key Set (9-Piece, CR-V, Torx + Metric)",
        "badge": "Hot",
        "price": "$0.55 - $0.80 /set",
        "moq": "MOQ 1 set",
        "img": "/images/ball-end-hex-key-set-9pcs.jpg",
        "src": "https://detail.1688.com/offer/911867791993.html",
        "desc": "Nine-piece hex and Torx key set that covers the sizes most common in machinery, furniture and electrical work. The chrome vanadium steel keys are hardened for a snug fit that resists stripping, and the ball-end long shafts let you drive fasteners at an angle in tight spaces. Sizes range from 1.5mm to 4mm hex plus T10 to T27 Torx, all organized in a molded orange holder that keeps them visible and within reach. A practical all-in-one set for technicians, assemblers, electricians and DIY users, and a compact add-on SKU for tool retailers stocking fastening essentials.",
        "specs": [
            ("Pieces", "9 (4 Hex + 5 Torx)"),
            ("Hex Sizes", "1.5, 2, 2.5, 3, 4 mm"),
            ("Torx Sizes", "T10 - T27"),
            ("Material", "Chrome Vanadium Steel"),
            ("Tips", "Ball-End Long Shafts"),
            ("Holder", "Orange Molded Case"),
        ],
        "points": [
            "Ball-end shafts - drive fasteners at an angle",
            "CR-V hardened steel resists stripping",
            "Hex + Torx in one compact holder",
            "Covers the most common service sizes",
            "Molded holder keeps sizes visible & in reach",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "magnetic-screwdriver-set", "mini-ratchet-handle-set"],
    },
    {
        "slug": "brushless-cordless-jigsaw",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Jigsaw (Bare Tool)",
        "badge": "Bestseller",
        "price": "$11.80 - $17.80 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/brushless-cordless-jigsaw.jpg",
        "src": "https://detail.1688.com/offer/808307542246.html",
        "desc": "Cordless jigsaw powered by a brushless motor for smooth, efficient cuts through wood, plywood, plastic and light metal. The tool-free blade clamp swaps blades in seconds, while the three-stage orbital action adjusts cutting speed to the material - straight cuts for dense wood, aggressive orbital cuts for fast work. The adjustable base plate tilts for bevel cuts up to 45 degrees, and the rubberized top handle with safety lock keeps one-hand control comfortable during long cuts. Sold as a bare tool to fit your existing 21V battery platform, it is a strong add-on for cordless tool ranges and a favorite of carpenters, joiners, electricians and DIY remodelers.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Blade", "Tool-Free Quick Clamp"),
            ("Orbital", "3-Stage Adjustable"),
            ("Base", "Adjustable Bevel"),
            ("Kit", "Bare Tool (Battery Sold Separately)"),
        ],
        "points": [
            "Brushless motor - efficient and long runtime",
            "Tool-free blade change in seconds",
            "3-stage orbital action for any material",
            "Fits a shared 21V battery platform",
            "Adjustable base - bevel cuts up to 45 degrees",
        ],
        "related": ["5-inch-brushless-circular-saw-kit", "brushless-cordless-drill", "brushless-cordless-angle-grinder"],
    },
    {
        "slug": "dual-temperature-heat-gun-110v",
        "cat": "power-tools",
        "name": "Dual-Temperature Heat Gun 2000W (110V, US Plug)",
        "badge": "New",
        "price": "$5.20 - $7.80 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/dual-temperature-heat-gun-110v.jpg",
        "src": "https://detail.1688.com/offer/674795350176.html",
        "desc": "2000W heat gun with two-speed temperature control for shrink tubing, paint stripping, adhesive softening, vinyl wrapping and electronics work. The red rocker switch selects high or low airflow, reaching up to 600 C for fast heat-shrink jobs or a gentler 300 C for sensitive materials. The compact blue body with hanging loop is comfortable in one hand, and the US 110V plug works straight out of the box in North American outlets. One tapered nozzle is included for concentrated airflow. A budget-friendly essential for installers, workshops, craftspeople and maintenance teams, and a dependable shelf filler for power-tool and accessory ranges.",
        "specs": [
            ("Power", "2000 W"),
            ("Voltage", "110 V (US Plug)"),
            ("Temperature", "300-600 C"),
            ("Airflow", "Two-Speed, 300-500 L/min"),
            ("Nozzle", "1 Tapered Included"),
            ("Applications", "Shrink Wrap, Stripping, Soldering"),
        ],
        "points": [
            "Two-speed control - 300 to 600 C",
            "2000W for fast heat-shrink work",
            "US 110V plug, ready to use",
            "Lightweight body with hanging loop",
            "Gentle 300C setting for sensitive materials",
        ],
        "related": ["hot-air-rework-station-858d", "brushless-cordless-drill", "corded-impact-drill-13mm"],
    },
    {
        "slug": "hot-air-rework-station-858d",
        "cat": "power-tools",
        "name": "Hot Air Rework Station 858D (110V, Digital Temp Display)",
        "badge": "Hot",
        "price": "$10.70 - $16.10 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/hot-air-rework-station-858d.jpg",
        "src": "https://detail.1688.com/offer/657569195240.html",
        "desc": "858D hot air rework station for soldering, desoldering and heat-shrink work on circuit boards and small components. The digital LED display shows the current temperature at a glance, and the air-flow dial plus temperature adjustment buttons give precise control for delicate SMD work. Three interchangeable nozzles cover different component sizes, and the ergonomic handpiece with stand keeps the station organized on the bench. The 110V US version plugs into standard outlets, and the CE-marked design suits electronics repair shops, phone repair services, hobbyists and training labs. A proven complement to hand-tools and power-tools ranges for repair-focused buyers.",
        "specs": [
            ("Model", "858D"),
            ("Display", "Digital LED Temperature"),
            ("Controls", "Calibration + Air Dial"),
            ("Voltage", "110 V (US)"),
            ("Nozzles", "3 Interchangeable"),
            ("Applications", "SMD Soldering, Heat Shrink"),
        ],
        "points": [
            "Digital temperature display - precise control",
            "Adjustable airflow dial 1-8",
            "3 nozzles for different component sizes",
            "CE-marked, 110V US plug",
            "Handpiece stand keeps the bench organized",
        ],
        "related": ["dual-temperature-heat-gun-110v", "magnetic-screwdriver-set", "diagonal-cutting-pliers"],
    },
    {
        "slug": "pistol-air-screwdriver-5h",
        "cat": "pneumatic-tools",
        "name": "Pistol-Grip Air Screwdriver (TPR-305L, Standard Kit)",
        "badge": "Bestseller",
        "price": "$13.10 - $19.60 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/pistol-air-screwdriver-5h.jpg",
        "src": "https://detail.1688.com/offer/989021347202.html",
        "desc": "Pistol-grip pneumatic screwdriver built for fast, consistent screw driving on production lines, assembly work and woodworking. The 5H-class tool drives up to 5mm capacity fasteners with 55Nm of torque at 12000rpm, and the trigger-style throttle plus direction switch give one-hand control for repetitive driving. The compact red body with textured grip stays comfortable through long shifts, and the standard package includes a screwdriver bit, hanging hook and air connector so you can hook it to a compressor hose immediately. A reliable addition for furniture factories, cabinet shops, electronics assembly and maintenance teams, and a strong SKU for pneumatic tool ranges.",
        "specs": [
            ("Model", "TPR-305L"),
            ("Capacity", "5 mm"),
            ("Torque", "55 Nm"),
            ("Speed", "12000 rpm"),
            ("Inlet", "1/4 inch NPT"),
            ("Kit", "Bit + Hook + Air Connector"),
        ],
        "points": [
            "55Nm torque - drives 5mm fasteners fast",
            "12000rpm for quick production work",
            "Standard kit - bit, hook and connector included",
            "Ergonomic pistol grip for long shifts",
            "Direction switch - fast forward & reverse",
        ],
        "related": ["air-impact-wrench", "high-pressure-air-blow-gun", "pneumatic-air-nailer"],
    },
    {
        "slug": "5-inch-air-polisher",
        "cat": "pneumatic-tools",
        "name": "5-Inch Air Polisher / Orbital Sander (POL-AB-215, 125mm)",
        "badge": "New",
        "price": "$14.40 - $21.70 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/5-inch-air-polisher.jpg",
        "src": "https://detail.1688.com/offer/795311939544.html",
        "desc": "Air-powered orbital sander and polisher with a 125mm (5 inch) pad for auto detailing, buffing, paint polishing and flat-surface sanding. The 12000rpm no-load speed with 5mm eccentric orbit delivers a smooth finish without swirl marks, while the palm-shaped blue grip and long trigger lever give steady control over long sessions. The hook-and-loop pad accepts standard 125mm discs for fast changeovers between sanding and polishing. Each unit ships with a wrench and air connector, and the non-suction design keeps the tool light and easy to handle. A practical companion to air spray guns and compressors for body shops, furniture workshops and detailing services.",
        "specs": [
            ("Pad", "5 inch / 125 mm"),
            ("No-Load Speed", "12000 rpm"),
            ("Eccentricity", "5 mm"),
            ("Type", "Orbital Sander / Polisher"),
            ("Gifts", "Wrench + Air Connector"),
            ("Applications", "Auto Detailing, Buffing, Sanding"),
        ],
        "points": [
            "12000rpm + 5mm orbit - smooth finish",
            "Hook-and-loop pad - fast disc changes",
            "Wrench and air connector included",
            "Companion to spray guns and compressors",
            "Non-suction design - light & easy handling",
        ],
        "related": ["rectangular-air-sander", "aluminum-siphon-spray-gun", "air-impact-wrench"],
    },
]
RELATED_INDEX = {p["slug"]: p for p in PRODUCTS}
