# -*- coding: utf-8 -*-
"""Best Hardware Tools site product data. Prices = FOB USD estimates (CNY/7.1)."""

SITE = {
    "brand": "Best Hardware Tools",
    "short": "BHT",
    "domain": "besthardwaretools.com",
    "tagline": "One-Stop Hardware & Tools Supplier for Global Buyers",
    "whatsapp": "8618669693290",
    "email": "yale@mahjongbest.com",
    "formspree": "xeeynyba",
    "ga4": "G-5J9VBPKTB4",
    "clarity": "xtrv7vr8dn",
    "bank_beneficiary": "Linyi Strawberry International Trade Co., Ltd",
    "bank_account": "63003927994",
    "bank_swift": "CHASHKHH / CHASHKHHXXX",
    "bank_note": "USD Payments: Recommend using US J.P. Morgan (CHASUS33) as transit bank to reduce forex risk. This account cannot receive payments from Russia and Belarus.",
}

CATEGORIES = [
    {"id": "hardware", "name": "Hardware", "nav": "Hardware"},
    {"id": "hand-tools", "name": "Hand Tools", "nav": "Hand Tools"},
    {"id": "power-tools", "name": "Power Tools", "nav": "Power Tools"},
    {"id": "pneumatic-tools", "name": "Pneumatic Tools", "nav": "Pneumatic Tools"},
]

PRODUCTS = [
    {
        "slug": "stainless-steel-soft-close-hinge",
        "cat": "hardware",
        "name": "304 Stainless Steel Hydraulic Soft-Close Hinge",
        "badge": "Bestseller",
        "price": "$0.28 - $0.42 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/stainless-steel-soft-close-hinge.jpg",
        "src": "https://detail.1688.com/offer/708534731229.html",
        "desc": "Precision-engineered 304 stainless steel hinge with integrated hydraulic damping for silent, soft-close cabinet doors. The 2.0mm thickened body delivers outstanding rigidity and long service life, while the self-closing mechanism protects cabinets from slamming damage. Ideal for kitchen cabinets, wardrobes and commercial furniture, this hinge suits both new builds and retrofits. Factory-direct supply supports custom finishes, bulk packaging and OEM branding for furniture manufacturers and hardware distributors worldwide.",
        "specs": [
            ("Material", "304 Stainless Steel"),
            ("Thickness", "2.0 mm"),
            ("Type", "Hydraulic Damping / Soft-Close"),
            ("Opening", "Full Overlay (Large Bend)"),
            ("Application", "Cabinet, Wardrobe, Kitchen Door"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Silent hydraulic soft-close prevents door slamming",
            "2.0mm 304 stainless steel - rust resistant & durable",
            "Self-locking clip-on design for fast installation",
            "Factory-direct with OEM & custom packaging support",
        ],
        "related": ["black-aluminum-cabinet-handle", "heavy-duty-swivel-caster", "72-tooth-ratchet-wrench-set"],
    },
    {
        "slug": "black-aluminum-cabinet-handle",
        "cat": "hardware",
        "name": "Black Anodized Aluminum Cabinet Handle / Drawer Pull",
        "badge": "Hot",
        "price": "$0.15 - $0.25 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/black-aluminum-cabinet-handle.jpg",
        "src": "https://detail.1688.com/offer/1037766581644.html",
        "desc": "Modern minimalist cabinet handle machined from solid aluminum with a durable anodized black finish. The clean, slim profile complements contemporary kitchens, wardrobes and office furniture. Available in multiple hole spacings (128mm standard) to match common cabinet panels. Each handle is precision-drilled for accurate alignment and ships with mounting screws. A popular choice for furniture makers, renovation projects and cross-border e-commerce sellers building hardware ranges.",
        "specs": [
            ("Material", "Aluminum Alloy"),
            ("Finish", "Anodized Black"),
            ("Hole Spacing", "128 mm (more sizes available)"),
            ("Style", "Modern Minimalist"),
            ("Application", "Cabinet, Drawer, Wardrobe"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Solid aluminum with scratch-resistant anodized finish",
            "Slim modern profile fits most furniture styles",
            "Multiple hole spacings for panel flexibility",
            "Screws included - ready to install",
        ],
        "related": ["stainless-steel-soft-close-hinge", "heavy-duty-swivel-caster", "magnetic-screwdriver-set"],
    },
    {
        "slug": "heavy-duty-swivel-caster",
        "cat": "hardware",
        "name": "Heavy Duty Swivel Caster Wheel with Brake",
        "badge": "New",
        "price": "$0.85 - $1.30 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/heavy-duty-swivel-caster.jpg",
        "src": "https://detail.1688.com/offer/728667477642.html",
        "desc": "Rugged swivel caster with integrated brake, built for trolleys, platform carts, racks and industrial equipment. The hardened rubber wheel delivers smooth, quiet rolling on hard floors while the reinforced steel bracket and ball-bearing swivel ensure heavy load capacity and 360-degree maneuverability. The side brake locks the wheel firmly in place for safe stationary work. Available in multiple sizes and load ratings to match your application. Factory-direct pricing for bulk importers and OEM projects.",
        "specs": [
            ("Wheel Diameter", "4 inch (more sizes available)"),
            ("Type", "Swivel with Brake"),
            ("Material", "Rubber Wheel + Steel Bracket"),
            ("Application", "Trolley, Platform Cart, Rack"),
            ("Feature", "360° Swivel, Side Brake"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Side brake locks wheel for safe stationary use",
            "Hardened rubber wheel - quiet on hard floors",
            "Reinforced steel bracket for heavy loads",
            "Multiple sizes & load ratings available",
        ],
        "related": ["stainless-steel-soft-close-hinge", "black-aluminum-cabinet-handle", "air-impact-wrench"],
    },
    {
        "slug": "72-tooth-ratchet-wrench-set",
        "cat": "hand-tools",
        "name": "72-Tooth Dual-Drive Rapid Ratchet Wrench",
        "badge": "Bestseller",
        "price": "$1.35 - $2.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/72-tooth-ratchet-wrench-set.jpg",
        "src": "https://detail.1688.com/offer/1060774840292.html",
        "desc": "High-efficiency dual-drive ratchet wrench combining open-end and box-end functions in one tool. The 72-tooth ratchet mechanism delivers a fine 5-degree swing arc, letting you work in tight spaces without re-positioning. Forged from hardened chrome vanadium steel with a corrosion-resistant black nickel finish and an anti-slip grip, it provides confident torque for automotive, machinery and general maintenance tasks. Available in multiple sizes and as complete sets.",
        "specs": [
            ("Material", "Chrome Vanadium Steel (CR-V)"),
            ("Ratchet", "72-Tooth / 5° Swing Arc"),
            ("Type", "Dual-Drive Open-End & Box-End"),
            ("Size", "13 mm (full size range available)"),
            ("Finish", "Black Nickel Anti-Corrosion"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "72-tooth ratchet - works in tight spaces",
            "Dual drive combines open-end & box-end",
            "Forged CR-V steel with anti-corrosion finish",
            "Ideal for automotive & machinery maintenance",
        ],
        "related": ["magnetic-screwdriver-set", "industrial-lineman-pliers", "brushless-impact-wrench"],
    },
    {
        "slug": "magnetic-screwdriver-set",
        "cat": "hand-tools",
        "name": "Industrial Magnetic Screwdriver Set (CR-V)",
        "badge": "Hot",
        "price": "$0.36 - $0.55 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/magnetic-screwdriver-set.jpg",
        "src": "https://detail.1688.com/offer/834783626722.html",
        "desc": "Professional-grade screwdriver set featuring hardened chrome vanadium steel shafts with strong magnetic tips that hold screws firmly during fastening. Ergonomic handles provide a comfortable, slip-resistant grip for extended working sessions. This set covers Phillips and slotted (flat) heads in multiple sizes, making it a versatile addition for electricians, mechanics, DIY users and assembly lines. Suitable for household repairs, appliance service and industrial maintenance.",
        "specs": [
            ("Material", "Chrome Vanadium Steel (CR-V)"),
            ("Tips", "Phillips & Slotted, Magnetic"),
            ("Length", "75 mm shaft (multi sizes)"),
            ("Handle", "Ergonomic Anti-Slip Grip"),
            ("Application", "Electrical, Assembly, DIY"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Strong magnetic tip holds screws securely",
            "Hardened CR-V steel - wear resistant",
            "Ergonomic grip for comfortable use",
            "Multi-size set covers common tasks",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "industrial-lineman-pliers", "brushless-cordless-drill"],
    },
    {
        "slug": "industrial-lineman-pliers",
        "cat": "hand-tools",
        "name": "Industrial Grade Lineman Pliers 6\" (CR-V Forged)",
        "badge": "Bestseller",
        "price": "$0.90 - $1.35 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/industrial-lineman-pliers.jpg",
        "src": "https://detail.1688.com/offer/576365440885.html",
        "desc": "Heavy-duty lineman pliers drop-forged from chrome vanadium steel with induction-hardened cutting edges that slice through wire, cable and light metal with ease. The multi-function design integrates cutting, gripping, crimping and stripping functions in one tool. A precision-aligned joint ensures smooth, consistent operation, while the TPR comfort grip reduces hand fatigue. A staple for electricians, construction workers and general trades.",
        "specs": [
            ("Material", "Chrome Vanadium Steel, Drop Forged"),
            ("Length", "6 inch (8/9 inch available)"),
            ("Type", "Lineman / Combination Pliers"),
            ("Functions", "Cutting, Gripping, Crimping"),
            ("Handle", "TPR Comfort Grip"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Drop-forged CR-V steel - strong & durable",
            "Induction-hardened cutting edges",
            "Multi-function: cut, grip, crimp, strip",
            "Comfort grip reduces hand fatigue",
        ],
        "related": ["72-tooth-ratchet-wrench-set", "magnetic-screwdriver-set", "pneumatic-air-nailer"],
    },
    {
        "slug": "brushless-cordless-drill",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Drill Kit (2 Batteries + Charger)",
        "badge": "Hot",
        "price": "$11.00 - $16.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-cordless-drill.jpg",
        "src": "https://detail.1688.com/offer/806889479426.html",
        "desc": "Powerful 21V brushless cordless drill delivering high efficiency and longer runtime than brushed motors. The variable-speed trigger, keyless chuck and LED work light make drilling and screw-driving fast and accurate in any job site condition. This complete kit includes two lithium batteries, a fast charger and a durable plastic case, ready for export. Excellent for carpenters, electricians, furniture assembly teams and DIY enthusiasts.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Kit Includes", "2 Batteries + Charger + Case"),
            ("Chuck", "Keyless"),
            ("Plug Standard", "EU / US (on request)"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "Brushless motor - more power, longer life",
            "Complete kit: 2 batteries + charger + case",
            "Variable speed & keyless chuck",
            "Ready for export with plug options",
        ],
        "related": ["brushless-cordless-angle-grinder", "brushless-impact-wrench", "magnetic-screwdriver-set"],
    },
    {
        "slug": "brushless-cordless-angle-grinder",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Angle Grinder 4.5\"",
        "badge": "New",
        "price": "$26.00 - $38.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-cordless-angle-grinder.jpg",
        "src": "https://detail.1688.com/offer/919795260450.html",
        "desc": "Versatile brushless cordless angle grinder with a rotating head for cutting, grinding, polishing and rust removal in hard-to-reach positions. The 21V brushless motor delivers consistent power with up to 7.5Ah battery capacity for extended working time. Features include tool-free guard adjustment, side handle for control and spindle lock for fast disc changes. Ideal for metalwork, construction, tile work and maintenance crews who need cordless freedom.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Disc Size", "100 mm / 4.5 inch"),
            ("Battery", "Up to 7.5 Ah (kit option)"),
            ("Head", "3-Axis Rotating"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "Rotating head reaches awkward angles",
            "Brushless motor with up to 7.5Ah runtime",
            "Cutting, grinding, polishing & rust removal",
            "Tool-free guard & spindle lock",
        ],
        "related": ["brushless-cordless-drill", "brushless-impact-wrench", "hvlp-gravity-spray-gun"],
    },
    {
        "slug": "brushless-impact-wrench",
        "cat": "power-tools",
        "name": "21V Brushless Cordless Impact Wrench (Model 285)",
        "badge": "Bestseller",
        "price": "$15.00 - $22.00 /kit",
        "moq": "MOQ 1 kit",
        "img": "/images/brushless-impact-wrench.jpg",
        "src": "https://detail.1688.com/offer/842431375043.html",
        "desc": "High-torque brushless cordless impact wrench purpose-built for automotive repair, scaffolding and construction fastening. The 21V brushless motor delivers rapid-impact torque to remove stubborn lug nuts and bolts, while the compact body fits tight engine bays. This export kit includes two 10-cell batteries and a fast charger. A dependable workhorse for mechanics, tire shops and field service teams.",
        "specs": [
            ("Voltage", "21 V Li-ion"),
            ("Motor", "Brushless"),
            ("Drive", "1/2 inch Square"),
            ("Battery", "2 × 10-Cell Li-ion"),
            ("Application", "Auto Repair, Scaffolding, Construction"),
            ("MOQ", "1 kit"),
        ],
        "points": [
            "High-torque impact for stubborn fasteners",
            "Brushless motor - longer runtime & life",
            "1/2\" drive fits standard sockets",
            "Export kit with 2 batteries + charger",
        ],
        "related": ["brushless-cordless-drill", "brushless-cordless-angle-grinder", "air-impact-wrench"],
    },
    {
        "slug": "air-impact-wrench",
        "cat": "pneumatic-tools",
        "name": "1/2\" Heavy Duty Air Impact Wrench (Pistol Grip)",
        "badge": "Hot",
        "price": "$30.00 - $44.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/air-impact-wrench.jpg",
        "src": "https://detail.1688.com/offer/683522828976.html",
        "desc": "Industrial-grade pneumatic impact wrench with high torque output for automotive tire service, machinery maintenance and heavy assembly work. The pistol-grip body is precision-balanced for comfortable control, and the twin-hammer mechanism delivers reliable, repeatable impact force. Built with a durable aluminum housing and ergonomic rubber grip, this tool connects to any standard air compressor for long, maintenance-free service. A cost-effective choice for garages and workshops worldwide.",
        "specs": [
            ("Drive", "1/2 inch"),
            ("Type", "Pistol Grip Impact Wrench"),
            ("Body", "Aluminum Housing"),
            ("Mechanism", "Twin-Hammer"),
            ("Application", "Auto Repair, Tire Service, Industry"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "High torque for lug nuts & bolts",
            "Twin-hammer mechanism - reliable power",
            "Lightweight aluminum body, ergonomic grip",
            "Works with standard air compressors",
        ],
        "related": ["pneumatic-air-nailer", "hvlp-gravity-spray-gun", "brushless-impact-wrench"],
    },
    {
        "slug": "pneumatic-air-nailer",
        "cat": "pneumatic-tools",
        "name": "Pneumatic Straight Nail Gun (F30 / 30mm)",
        "badge": "Bestseller",
        "price": "$6.00 - $9.00 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/pneumatic-air-nailer.jpg",
        "src": "https://detail.1688.com/offer/570819195363.html",
        "desc": "Reliable pneumatic straight nailer designed for cabinet making, furniture assembly, trim work and general woodworking. Fires 30mm F-type finish nails with consistent depth control, and the anti-jam magazine keeps production moving. The lightweight aluminum body and comfortable grip reduce operator fatigue during long shifts. Connects to any standard air compressor with a quick-connect fitting. A practical addition to any workshop or production line.",
        "specs": [
            ("Fastener", "F30 Straight Nails (30 mm)"),
            ("Magazine", "Anti-Jam Design"),
            ("Body", "Lightweight Aluminum"),
            ("Application", "Woodworking, Furniture, Trim"),
            ("Air Supply", "Standard Compressor"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Anti-jam magazine for non-stop work",
            "30mm F-type finish nails",
            "Lightweight - reduces fatigue",
            "Perfect for furniture & woodworking",
        ],
        "related": ["air-impact-wrench", "hvlp-gravity-spray-gun", "industrial-lineman-pliers"],
    },
    {
        "slug": "hvlp-gravity-spray-gun",
        "cat": "pneumatic-tools",
        "name": "HVLP Gravity Spray Gun 1.4mm Nozzle (H827)",
        "badge": "Hot",
        "price": "$5.00 - $7.50 /pc",
        "moq": "MOQ 1 pc",
        "img": "/images/hvlp-gravity-spray-gun.jpg",
        "src": "https://detail.1688.com/offer/653316938139.html",
        "desc": "Professional HVLP gravity-feed spray gun delivering fine, even atomization for automotive topcoats, primers, furniture finishes and industrial coatings. The 1.4mm nozzle balances flow rate and finish quality for both base and clear coats. Anodized aluminum body with stainless steel needle and nozzle ensures corrosion resistance and easy cleaning. Precise air and fluid controls give painters full command over pattern width and material delivery. Excellent value for body shops and finishing workshops.",
        "specs": [
            ("Type", "HVLP Gravity Feed"),
            ("Nozzle", "1.4 mm"),
            ("Cup", "600 ml Top Cup Included"),
            ("Body", "Anodized Aluminum"),
            ("Application", "Auto Paint, Primer, Furniture Finish"),
            ("MOQ", "1 pc"),
        ],
        "points": [
            "Fine atomization - smooth professional finish",
            "1.4mm nozzle suits base & clear coats",
            "Stainless needle & nozzle - easy clean",
            "Precise air & fluid adjustment controls",
        ],
        "related": ["pneumatic-air-nailer", "air-impact-wrench", "brushless-cordless-angle-grinder"],
    },
]

RELATED_INDEX = {p["slug"]: p for p in PRODUCTS}
